# Railway.toml - Configuration for separate backend and frontend services
# Note: Deploy these as separate Railway services, not together

# This file is for reference only - Railway will auto-detect each service
# when you set the root directory for each service separately