# Generated by Django 4.2.7 on 2025-08-09 15:06

from decimal import Decimal
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BankAccount',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Számla neve')),
                ('account_number', models.CharField(max_length=50, unique=True, verbose_name='Számlaszám')),
                ('is_default', models.BooleanField(default=False, verbose_name='Alapértelmezett')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Bank számla',
                'verbose_name_plural': 'Bank számlák',
            },
        ),
        migrations.CreateModel(
            name='Beneficiary',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Kedvezményezett neve')),
                ('account_number', models.CharField(max_length=50, verbose_name='Számlaszám')),
                ('bank_name', models.CharField(blank=True, max_length=200, verbose_name='Bank neve')),
                ('is_frequent', models.BooleanField(default=False, verbose_name='Gyakori kedvezményezett')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Kedvezményezett',
                'verbose_name_plural': 'Kedvezményezettek',
                'unique_together': {('name', 'account_number')},
            },
        ),
        migrations.CreateModel(
            name='Transfer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=15, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))], verbose_name='Összeg')),
                ('currency', models.CharField(choices=[('HUF', 'HUF'), ('EUR', 'EUR'), ('USD', 'USD')], default='HUF', max_length=3, verbose_name='Pénznem')),
                ('execution_date', models.DateField(verbose_name='Teljesítési dátum')),
                ('remittance_info', models.CharField(max_length=500, verbose_name='Közlemény')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('beneficiary', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bank_transfers.beneficiary', verbose_name='Kedvezményezett')),
                ('originator_account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bank_transfers.bankaccount', verbose_name='Terhelendő számla')),
            ],
            options={
                'verbose_name': 'Utalás',
                'verbose_name_plural': 'Utalások',
            },
        ),
        migrations.CreateModel(
            name='TransferTemplate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Sablon neve')),
                ('description', models.TextField(blank=True, verbose_name='Leírás')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Utalási sablon',
                'verbose_name_plural': 'Utalási sablonok',
            },
        ),
        migrations.CreateModel(
            name='TransferBatch',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Köteg neve')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('xml_generated_at', models.DateTimeField(blank=True, null=True, verbose_name='XML generálás ideje')),
                ('transfers', models.ManyToManyField(to='bank_transfers.transfer', verbose_name='Utalások')),
            ],
            options={
                'verbose_name': 'Utalási köteg',
                'verbose_name_plural': 'Utalási kötegek',
            },
        ),
        migrations.AddField(
            model_name='transfer',
            name='template',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='bank_transfers.transfertemplate', verbose_name='Sablon'),
        ),
    ]
