# Generated by Django 4.2.7 on 2025-08-09 15:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('bank_transfers', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='TemplateBeneficiary',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('default_amount', models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True)),
                ('default_remittance', models.CharField(blank=True, max_length=500)),
                ('order', models.IntegerField(default=0, verbose_name='Sorrend')),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Sablon kedvezményezett',
                'verbose_name_plural': 'Sablon kedvezményezettek',
                'ordering': ['order', 'beneficiary__name'],
            },
        ),
        migrations.AlterModelOptions(
            name='bankaccount',
            options={'ordering': ['-is_default', 'name'], 'verbose_name': 'Bank számla', 'verbose_name_plural': 'Bank számlák'},
        ),
        migrations.AlterModelOptions(
            name='beneficiary',
            options={'ordering': ['name'], 'verbose_name': 'Kedvezményezett', 'verbose_name_plural': 'Kedvezményezettek'},
        ),
        migrations.AlterModelOptions(
            name='transfer',
            options={'ordering': ['-execution_date', '-created_at'], 'verbose_name': 'Utalás', 'verbose_name_plural': 'Utalások'},
        ),
        migrations.AlterModelOptions(
            name='transferbatch',
            options={'ordering': ['-created_at'], 'verbose_name': 'Utalási köteg', 'verbose_name_plural': 'Utalási kötegek'},
        ),
        migrations.AlterModelOptions(
            name='transfertemplate',
            options={'ordering': ['name'], 'verbose_name': 'Utalási sablon', 'verbose_name_plural': 'Utalási sablonok'},
        ),
        migrations.AlterUniqueTogether(
            name='beneficiary',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='bankaccount',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='beneficiary',
            name='is_active',
            field=models.BooleanField(default=True, verbose_name='Aktív'),
        ),
        migrations.AddField(
            model_name='beneficiary',
            name='notes',
            field=models.TextField(blank=True, verbose_name='Megjegyzések'),
        ),
        migrations.AddField(
            model_name='beneficiary',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='transfer',
            name='is_processed',
            field=models.BooleanField(default=False, verbose_name='Feldolgozva'),
        ),
        migrations.AddField(
            model_name='transfer',
            name='notes',
            field=models.TextField(blank=True, verbose_name='Megjegyzések'),
        ),
        migrations.AddField(
            model_name='transfer',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='transferbatch',
            name='description',
            field=models.TextField(blank=True, verbose_name='Leírás'),
        ),
        migrations.AddField(
            model_name='transferbatch',
            name='total_amount',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=15, verbose_name='Összeg'),
        ),
        migrations.AddField(
            model_name='transfertemplate',
            name='is_active',
            field=models.BooleanField(default=True, verbose_name='Aktív'),
        ),
        migrations.AddField(
            model_name='transfertemplate',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddIndex(
            model_name='beneficiary',
            index=models.Index(fields=['name'], name='bank_transf_name_f301cf_idx'),
        ),
        migrations.AddIndex(
            model_name='beneficiary',
            index=models.Index(fields=['is_frequent'], name='bank_transf_is_freq_6b074c_idx'),
        ),
        migrations.AddIndex(
            model_name='beneficiary',
            index=models.Index(fields=['is_active'], name='bank_transf_is_acti_8b6007_idx'),
        ),
        migrations.AddIndex(
            model_name='transfer',
            index=models.Index(fields=['execution_date'], name='bank_transf_executi_f48030_idx'),
        ),
        migrations.AddIndex(
            model_name='transfer',
            index=models.Index(fields=['is_processed'], name='bank_transf_is_proc_93fa8d_idx'),
        ),
        migrations.AddIndex(
            model_name='transfer',
            index=models.Index(fields=['created_at'], name='bank_transf_created_359e92_idx'),
        ),
        migrations.AddField(
            model_name='templatebeneficiary',
            name='beneficiary',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bank_transfers.beneficiary'),
        ),
        migrations.AddField(
            model_name='templatebeneficiary',
            name='template',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='template_beneficiaries', to='bank_transfers.transfertemplate'),
        ),
        migrations.AlterUniqueTogether(
            name='templatebeneficiary',
            unique_together={('template', 'beneficiary')},
        ),
    ]
