# Generated by Django 4.2.7 on 2025-08-10 19:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bank_transfers', '0003_rename_beneficiary_fields'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='transfer',
            options={'ordering': ['order', '-execution_date', '-created_at'], 'verbose_name': 'Utalás', 'verbose_name_plural': 'Utalások'},
        ),
        migrations.AddField(
            model_name='transfer',
            name='order',
            field=models.IntegerField(default=0, help_text='Átutalások sorrendje XML generáláskor', verbose_name='Sorrend'),
        ),
    ]
