# Generated by Django 4.2.7 on 2025-08-11 05:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bank_transfers', '0004_alter_transfer_options_transfer_order'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='transferbatch',
            options={'ordering': ['order', '-created_at'], 'verbose_name': 'Utalási köteg', 'verbose_name_plural': 'Utalási kötegek'},
        ),
        migrations.AddField(
            model_name='transferbatch',
            name='bank_usage_date',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Bank felhasználás dátuma'),
        ),
        migrations.AddField(
            model_name='transferbatch',
            name='order',
            field=models.IntegerField(default=0, help_text='Kötegek sorrendje a listázáshoz és letöltéshez', verbose_name='Sorrend'),
        ),
        migrations.AddField(
            model_name='transferbatch',
            name='used_in_bank',
            field=models.BooleanField(default=False, help_text='Jelzi, hogy az XML fájl fel lett-e töltve az internetbankba', verbose_name='Felhasználva a bankban'),
        ),
        migrations.AddField(
            model_name='transferbatch',
            name='xml_content',
            field=models.TextField(blank=True, help_text='Generált XML fájl tartalma', verbose_name='XML tartalom'),
        ),
    ]
