# Generated by Django 4.2.7 on 2025-08-11 05:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bank_transfers', '0005_alter_transferbatch_options_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='transferbatch',
            name='xml_content',
        ),
    ]
