# Generated by Django 4.2.7 on 2025-08-14 18:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bank_transfers', '0006_remove_xml_content'),
    ]

    operations = [
        migrations.AddField(
            model_name='templatebeneficiary',
            name='default_execution_date',
            field=models.DateField(blank=True, null=True, verbose_name='Alapértelmezett teljesítési dátum'),
        ),
    ]
