# Generated by Django 4.2.7 on 2025-08-17 16:26

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('bank_transfers', '0007_templatebeneficiary_default_execution_date'),
    ]

    operations = [
        migrations.CreateModel(
            name='Company',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Cég neve')),
                ('tax_id', models.CharField(max_length=20, unique=True, verbose_name='Adószám')),
                ('address', models.TextField(blank=True, verbose_name='Cím')),
                ('phone', models.CharField(blank=True, max_length=50, verbose_name='Telefon')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='E-mail')),
                ('is_active', models.BooleanField(default=True, verbose_name='Aktív')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Cég',
                'verbose_name_plural': 'Cégek',
                'ordering': ['name'],
            },
        ),
        migrations.AddField(
            model_name='bankaccount',
            name='bank_name',
            field=models.CharField(blank=True, max_length=200, verbose_name='Bank neve'),
        ),
        migrations.AlterField(
            model_name='bankaccount',
            name='account_number',
            field=models.CharField(max_length=50, verbose_name='Számlaszám'),
        ),
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone', models.CharField(blank=True, max_length=50, verbose_name='Telefon')),
                ('preferred_language', models.CharField(default='hu', max_length=10, verbose_name='Nyelv')),
                ('timezone', models.CharField(default='Europe/Budapest', max_length=50, verbose_name='Időzóna')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('last_active_company', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='bank_transfers.company', verbose_name='Utoljára aktív cég')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Felhasználói profil',
                'verbose_name_plural': 'Felhasználói profilok',
            },
        ),
        migrations.AddField(
            model_name='bankaccount',
            name='company',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='bank_accounts', to='bank_transfers.company', verbose_name='Cég'),
        ),
        migrations.AddField(
            model_name='beneficiary',
            name='company',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='beneficiaries', to='bank_transfers.company', verbose_name='Cég'),
        ),
        migrations.AddField(
            model_name='transferbatch',
            name='company',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='transfer_batches', to='bank_transfers.company', verbose_name='Cég'),
        ),
        migrations.AddField(
            model_name='transfertemplate',
            name='company',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='transfer_templates', to='bank_transfers.company', verbose_name='Cég'),
        ),
        migrations.AlterUniqueTogether(
            name='bankaccount',
            unique_together={('company', 'account_number')},
        ),
        migrations.AlterUniqueTogether(
            name='transfertemplate',
            unique_together={('company', 'name')},
        ),
        migrations.CreateModel(
            name='CompanyUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(choices=[('ADMIN', 'Cég adminisztrátor'), ('USER', 'Felhasználó')], default='USER', max_length=10, verbose_name='Szerepkör')),
                ('is_active', models.BooleanField(default=True, verbose_name='Aktív')),
                ('joined_at', models.DateTimeField(auto_now_add=True)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='users', to='bank_transfers.company')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='company_memberships', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Cég felhasználó',
                'verbose_name_plural': 'Cég felhasználók',
                'ordering': ['company__name', 'user__last_name', 'user__first_name'],
                'unique_together': {('user', 'company')},
            },
        ),
    ]
