# Generated by Django 4.2.7 on 2025-08-17 16:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bank_transfers', '0009_populate_default_company'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='bankaccount',
            unique_together=set(),
        ),
        migrations.AlterUniqueTogether(
            name='transfertemplate',
            unique_together=set(),
        ),
    ]
