# Generated by Django 4.2.7 on 2025-08-22 18:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('bank_transfers', '0010_alter_bankaccount_unique_together_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Invoice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nav_invoice_number', models.CharField(max_length=100, verbose_name='NAV számlaszám')),
                ('invoice_direction', models.CharField(choices=[('INBOUND', 'Bejövő számla'), ('OUTBOUND', 'Kimenő számla')], max_length=10, verbose_name='Irány')),
                ('supplier_name', models.CharField(max_length=200, verbose_name='Szállító neve')),
                ('supplier_tax_number', models.CharField(blank=True, max_length=20, verbose_name='Szállító adószáma')),
                ('customer_name', models.CharField(max_length=200, verbose_name='Vevő neve')),
                ('customer_tax_number', models.CharField(blank=True, max_length=20, verbose_name='Vevő adószáma')),
                ('issue_date', models.DateField(verbose_name='Kiállítás dátuma')),
                ('fulfillment_date', models.DateField(blank=True, null=True, verbose_name='Teljesítés dátuma')),
                ('payment_due_date', models.DateField(blank=True, null=True, verbose_name='Fizetési határidő')),
                ('currency_code', models.CharField(default='HUF', max_length=3, verbose_name='Pénznem')),
                ('invoice_net_amount', models.DecimalField(decimal_places=2, max_digits=15, verbose_name='Nettó összeg')),
                ('invoice_vat_amount', models.DecimalField(decimal_places=2, max_digits=15, verbose_name='ÁFA összeg')),
                ('invoice_gross_amount', models.DecimalField(decimal_places=2, max_digits=15, verbose_name='Bruttó összeg')),
                ('original_request_version', models.CharField(max_length=10, verbose_name='NAV verzió')),
                ('completion_date', models.DateTimeField(blank=True, null=True, verbose_name='NAV feldolgozás dátuma')),
                ('source', models.CharField(default='NAV_SYNC', max_length=20, verbose_name='Forrás')),
                ('nav_transaction_id', models.CharField(blank=True, max_length=100, verbose_name='NAV tranzakció azonosító')),
                ('last_modified_date', models.DateTimeField(verbose_name='Utolsó módosítás (NAV)')),
                ('sync_status', models.CharField(choices=[('SUCCESS', 'Sikeres'), ('PARTIAL', 'Részleges'), ('FAILED', 'Sikertelen')], default='SUCCESS', max_length=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='invoices', to='bank_transfers.company')),
            ],
            options={
                'verbose_name': 'Számla',
                'verbose_name_plural': 'Számlák',
                'ordering': ['-issue_date', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='NavConfiguration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tax_number', models.CharField(max_length=20, verbose_name='NAV adószám')),
                ('technical_user_login', models.CharField(max_length=100, verbose_name='Technikai felhasználó')),
                ('technical_user_password', models.TextField(verbose_name='Jelszó (titkosítva)')),
                ('signing_key', models.TextField(verbose_name='Aláíró kulcs (titkosítva)')),
                ('exchange_key', models.TextField(verbose_name='Csere kulcs (titkosítva)')),
                ('company_encryption_key', models.TextField(verbose_name='Cég titkosítási kulcs (titkosítva)')),
                ('api_environment', models.CharField(choices=[('test', 'Test'), ('production', 'Éles')], default='test', max_length=10, verbose_name='API környezet')),
                ('is_active', models.BooleanField(default=True, verbose_name='Aktív')),
                ('sync_enabled', models.BooleanField(default=False, verbose_name='Szinkronizáció engedélyezett')),
                ('last_sync_timestamp', models.DateTimeField(blank=True, null=True, verbose_name='Utolsó szinkronizáció')),
                ('sync_frequency_hours', models.IntegerField(default=12, verbose_name='Szinkronizáció gyakorisága (óra)')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('company', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='nav_config', to='bank_transfers.company')),
            ],
            options={
                'verbose_name': 'NAV konfiguráció',
                'verbose_name_plural': 'NAV konfigurációk',
            },
        ),
        migrations.CreateModel(
            name='InvoiceSyncLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sync_start_time', models.DateTimeField(verbose_name='Szinkronizáció kezdete')),
                ('sync_end_time', models.DateTimeField(blank=True, null=True, verbose_name='Szinkronizáció vége')),
                ('direction_synced', models.CharField(max_length=10, verbose_name='Szinkronizált irány')),
                ('invoices_processed', models.IntegerField(default=0, verbose_name='Feldolgozott számlák')),
                ('invoices_created', models.IntegerField(default=0, verbose_name='Létrehozott számlák')),
                ('invoices_updated', models.IntegerField(default=0, verbose_name='Frissített számlák')),
                ('errors_count', models.IntegerField(default=0, verbose_name='Hibák száma')),
                ('last_error_message', models.TextField(blank=True, verbose_name='Utolsó hibaüzenet')),
                ('sync_status', models.CharField(choices=[('RUNNING', 'Futás'), ('SUCCESS', 'Sikeres'), ('PARTIAL_SUCCESS', 'Részlegesen sikeres'), ('FAILED', 'Sikertelen')], default='RUNNING', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sync_logs', to='bank_transfers.company')),
            ],
            options={
                'verbose_name': 'Szinkronizáció napló',
                'verbose_name_plural': 'Szinkronizáció naplók',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='InvoiceLineItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('line_number', models.IntegerField(verbose_name='Sor száma')),
                ('line_description', models.TextField(verbose_name='Megnevezés')),
                ('quantity', models.DecimalField(blank=True, decimal_places=3, max_digits=10, null=True, verbose_name='Mennyiség')),
                ('unit_of_measure', models.CharField(blank=True, max_length=50, verbose_name='Mértékegység')),
                ('unit_price', models.DecimalField(blank=True, decimal_places=4, max_digits=15, null=True, verbose_name='Egységár')),
                ('line_net_amount', models.DecimalField(decimal_places=2, max_digits=15, verbose_name='Sor nettó összeg')),
                ('vat_rate', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True, verbose_name='ÁFA kulcs (%)')),
                ('line_vat_amount', models.DecimalField(decimal_places=2, max_digits=15, verbose_name='Sor ÁFA összeg')),
                ('line_gross_amount', models.DecimalField(decimal_places=2, max_digits=15, verbose_name='Sor bruttó összeg')),
                ('product_code_category', models.CharField(blank=True, max_length=50, verbose_name='Termékkód kategória')),
                ('product_code_value', models.CharField(blank=True, max_length=100, verbose_name='Termékkód érték')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('invoice', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='line_items', to='bank_transfers.invoice')),
            ],
            options={
                'verbose_name': 'Számla tétel',
                'verbose_name_plural': 'Számla tételek',
                'ordering': ['line_number'],
                'unique_together': {('invoice', 'line_number')},
            },
        ),
        migrations.AddIndex(
            model_name='invoice',
            index=models.Index(fields=['company', 'invoice_direction'], name='bank_transf_company_92de58_idx'),
        ),
        migrations.AddIndex(
            model_name='invoice',
            index=models.Index(fields=['issue_date'], name='bank_transf_issue_d_11bb8e_idx'),
        ),
        migrations.AddIndex(
            model_name='invoice',
            index=models.Index(fields=['supplier_tax_number'], name='bank_transf_supplie_19a0f5_idx'),
        ),
        migrations.AddIndex(
            model_name='invoice',
            index=models.Index(fields=['customer_tax_number'], name='bank_transf_custome_3066a7_idx'),
        ),
        migrations.AddIndex(
            model_name='invoice',
            index=models.Index(fields=['nav_invoice_number'], name='bank_transf_nav_inv_e8c2f0_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='invoice',
            unique_together={('company', 'nav_invoice_number', 'invoice_direction')},
        ),
    ]
