# Generated by Django 4.2.7 on 2025-08-22 18:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bank_transfers', '0011_nav_invoice_models'),
    ]

    operations = [
        migrations.AddField(
            model_name='navconfiguration',
            name='certificate_password',
            field=models.CharField(blank=True, help_text='Kliens tanúsítvány jelszava (titkosítva tárolva)', max_length=500, verbose_name='Tanúsítvány jelszó'),
        ),
        migrations.AddField(
            model_name='navconfiguration',
            name='client_certificate',
            field=models.FileField(blank=True, help_text='NAV kliens tanúsítvány fájl (opcionális)', null=True, upload_to='nav_certificates/', verbose_name='Kliens tanúsítvány (.p12/.pfx)'),
        ),
        migrations.AlterField(
            model_name='navconfiguration',
            name='company_encryption_key',
            field=models.TextField(blank=True, verbose_name='Cég titkosítási kulcs'),
        ),
        migrations.AlterField(
            model_name='navconfiguration',
            name='exchange_key',
            field=models.TextField(verbose_name='Csere kulcs'),
        ),
        migrations.AlterField(
            model_name='navconfiguration',
            name='signing_key',
            field=models.TextField(verbose_name='Aláíró kulcs'),
        ),
        migrations.AlterField(
            model_name='navconfiguration',
            name='technical_user_password',
            field=models.TextField(verbose_name='Technikai felhasználó jelszó'),
        ),
    ]
