# Generated by Django 4.2.7 on 2025-08-23 05:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bank_transfers', '0012_navconfiguration_certificate_password_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='navconfiguration',
            name='exchange_key',
        ),
        migrations.RemoveField(
            model_name='navconfiguration',
            name='signing_key',
        ),
        migrations.RemoveField(
            model_name='navconfiguration',
            name='technical_user_login',
        ),
        migrations.RemoveField(
            model_name='navconfiguration',
            name='technical_user_password',
        ),
        migrations.AddField(
            model_name='navconfiguration',
            name='prod_exchange_key',
            field=models.TextField(blank=True, verbose_name='Éles csere kulcs'),
        ),
        migrations.AddField(
            model_name='navconfiguration',
            name='prod_signing_key',
            field=models.TextField(blank=True, verbose_name='Éles aláíró kulcs'),
        ),
        migrations.AddField(
            model_name='navconfiguration',
            name='prod_technical_user_login',
            field=models.CharField(blank=True, max_length=100, verbose_name='Éles technikai felhasználó'),
        ),
        migrations.AddField(
            model_name='navconfiguration',
            name='prod_technical_user_password',
            field=models.TextField(blank=True, verbose_name='Éles technikai felhasználó jelszó'),
        ),
        migrations.AddField(
            model_name='navconfiguration',
            name='test_exchange_key',
            field=models.TextField(blank=True, verbose_name='Test csere kulcs'),
        ),
        migrations.AddField(
            model_name='navconfiguration',
            name='test_signing_key',
            field=models.TextField(blank=True, verbose_name='Test aláíró kulcs'),
        ),
        migrations.AddField(
            model_name='navconfiguration',
            name='test_technical_user_login',
            field=models.CharField(blank=True, max_length=100, verbose_name='Test technikai felhasználó'),
        ),
        migrations.AddField(
            model_name='navconfiguration',
            name='test_technical_user_password',
            field=models.TextField(blank=True, verbose_name='Test technikai felhasználó jelszó'),
        ),
    ]
