# Generated by Django 4.2.7 on 2025-08-23 05:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('bank_transfers', '0013_nav_dual_credentials'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='navconfiguration',
            name='prod_exchange_key',
        ),
        migrations.RemoveField(
            model_name='navconfiguration',
            name='prod_signing_key',
        ),
        migrations.RemoveField(
            model_name='navconfiguration',
            name='prod_technical_user_login',
        ),
        migrations.RemoveField(
            model_name='navconfiguration',
            name='prod_technical_user_password',
        ),
        migrations.RemoveField(
            model_name='navconfiguration',
            name='test_exchange_key',
        ),
        migrations.RemoveField(
            model_name='navconfiguration',
            name='test_signing_key',
        ),
        migrations.RemoveField(
            model_name='navconfiguration',
            name='test_technical_user_login',
        ),
        migrations.RemoveField(
            model_name='navconfiguration',
            name='test_technical_user_password',
        ),
        migrations.AddField(
            model_name='navconfiguration',
            name='exchange_key',
            field=models.TextField(default='', verbose_name='Csere kulcs'),
        ),
        migrations.AddField(
            model_name='navconfiguration',
            name='signing_key',
            field=models.TextField(default='', verbose_name='Aláíró kulcs'),
        ),
        migrations.AddField(
            model_name='navconfiguration',
            name='technical_user_login',
            field=models.CharField(default='', max_length=100, verbose_name='Technikai felhasználó'),
        ),
        migrations.AddField(
            model_name='navconfiguration',
            name='technical_user_password',
            field=models.TextField(default='', verbose_name='Technikai felhasználó jelszó'),
        ),
        migrations.AlterField(
            model_name='navconfiguration',
            name='company',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='nav_configs', to='bank_transfers.company'),
        ),
    ]
