# Generated by Django 4.2.7 on 2025-08-23 06:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bank_transfers', '0014_revert_nav_to_foreignkey'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='navconfiguration',
            name='certificate_password',
        ),
        migrations.RemoveField(
            model_name='navconfiguration',
            name='client_certificate',
        ),
    ]
