# Generated by Django 4.2.7 on 2025-08-23 15:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bank_transfers', '0015_remove_nav_certificate_fields'),
    ]

    operations = [
        migrations.AddField(
            model_name='invoice',
            name='completeness_indicator',
            field=models.BooleanField(blank=True, null=True, verbose_name='Teljesség jelző'),
        ),
        migrations.AddField(
            model_name='invoice',
            name='invoice_appearance',
            field=models.CharField(blank=True, max_length=20, verbose_name='Számla megjelenés (PAPER/ELECTRONIC)'),
        ),
        migrations.AddField(
            model_name='invoice',
            name='invoice_category',
            field=models.CharField(blank=True, max_length=20, verbose_name='Számla kategória (NORMAL/SIMPLIFIED)'),
        ),
        migrations.AddField(
            model_name='invoice',
            name='invoice_gross_amount_huf',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True, verbose_name='Bruttó összeg (HUF)'),
        ),
        migrations.AddField(
            model_name='invoice',
            name='invoice_index',
            field=models.IntegerField(blank=True, null=True, verbose_name='Számla index'),
        ),
        migrations.AddField(
            model_name='invoice',
            name='invoice_net_amount_huf',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True, verbose_name='Nettó összeg (HUF)'),
        ),
        migrations.AddField(
            model_name='invoice',
            name='invoice_operation',
            field=models.CharField(blank=True, max_length=20, verbose_name='Számla művelet (CREATE/STORNO/MODIFY)'),
        ),
        migrations.AddField(
            model_name='invoice',
            name='invoice_vat_amount_huf',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True, verbose_name='ÁFA összeg (HUF)'),
        ),
        migrations.AddField(
            model_name='invoice',
            name='modification_index',
            field=models.IntegerField(blank=True, null=True, verbose_name='Módosítási index'),
        ),
        migrations.AddField(
            model_name='invoice',
            name='nav_creation_date',
            field=models.DateTimeField(blank=True, null=True, verbose_name='NAV létrehozási dátum'),
        ),
        migrations.AddField(
            model_name='invoice',
            name='nav_source',
            field=models.CharField(blank=True, max_length=10, verbose_name='NAV forrás (OSZ/XML)'),
        ),
        migrations.AddField(
            model_name='invoice',
            name='original_invoice_number',
            field=models.CharField(blank=True, max_length=100, verbose_name='Eredeti számla száma (storno esetén)'),
        ),
        migrations.AddField(
            model_name='invoice',
            name='payment_date',
            field=models.DateField(blank=True, null=True, verbose_name='Fizetési dátum'),
        ),
        migrations.AddField(
            model_name='invoice',
            name='payment_method',
            field=models.CharField(blank=True, max_length=20, verbose_name='Fizetési mód (TRANSFER/CASH/CARD)'),
        ),
    ]
