# Generated by Django 4.2.7 on 2025-08-23 15:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bank_transfers', '0016_add_nav_business_fields'),
    ]

    operations = [
        migrations.AlterField(
            model_name='invoice',
            name='invoice_appearance',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='Számla megjelenés (PAPER/ELECTRONIC)'),
        ),
        migrations.AlterField(
            model_name='invoice',
            name='invoice_category',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='Számla kategória (NORMAL/SIMPLIFIED)'),
        ),
        migrations.AlterField(
            model_name='invoice',
            name='invoice_operation',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='Számla művelet (CREATE/STORNO/MODIFY)'),
        ),
        migrations.AlterField(
            model_name='invoice',
            name='nav_source',
            field=models.CharField(blank=True, max_length=10, null=True, verbose_name='NAV forrás (OSZ/XML)'),
        ),
        migrations.AlterField(
            model_name='invoice',
            name='original_invoice_number',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Eredeti számla száma (storno esetén)'),
        ),
        migrations.AlterField(
            model_name='invoice',
            name='payment_method',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='Fizetési mód (TRANSFER/CASH/CARD)'),
        ),
    ]
