# Generated by Django 4.2.7 on 2025-08-23 16:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bank_transfers', '0017_fix_nav_fields_nullable'),
    ]

    operations = [
        migrations.AddField(
            model_name='invoice',
            name='batch_index',
            field=models.IntegerField(blank=True, null=True, verbose_name='Köteg index'),
        ),
    ]
