# Generated by Django 4.2.7 on 2025-08-23 21:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bank_transfers', '0018_add_batch_index_field'),
    ]

    operations = [
        migrations.AddField(
            model_name='invoice',
            name='nav_invoice_hash',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='NAV számla hash'),
        ),
        migrations.AddField(
            model_name='invoice',
            name='nav_invoice_xml',
            field=models.TextField(blank=True, null=True, verbose_name='NAV számla XML'),
        ),
    ]
