# Generated by Django 4.2.7 on 2025-08-24 12:18

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('bank_transfers', '0019_invoice_nav_invoice_hash_invoice_nav_invoice_xml'),
    ]

    operations = [
        migrations.AddField(
            model_name='transferbatch',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, default=django.utils.timezone.now, verbose_name='Módosítva'),
            preserve_default=False,
        ),
    ]
