# Generated by Django 4.2.7 on 2025-08-25 04:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('bank_transfers', '0020_auto_20250824_1418'),
    ]

    operations = [
        migrations.AddField(
            model_name='invoicelineitem',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='Módosítva'),
        ),
        migrations.AddField(
            model_name='invoicesynclog',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='Módosítva'),
        ),
        migrations.AlterField(
            model_name='bankaccount',
            name='company',
            field=models.ForeignKey(default=4, help_text='A modell tulajdonosa', on_delete=django.db.models.deletion.CASCADE, to='bank_transfers.company', verbose_name='Cég'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='bankaccount',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Létrehozva'),
        ),
        migrations.AlterField(
            model_name='bankaccount',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='Módosítva'),
        ),
        migrations.AlterField(
            model_name='beneficiary',
            name='company',
            field=models.ForeignKey(default=4, help_text='A modell tulajdonosa', on_delete=django.db.models.deletion.CASCADE, to='bank_transfers.company', verbose_name='Cég'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='beneficiary',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Létrehozva'),
        ),
        migrations.AlterField(
            model_name='beneficiary',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='Módosítva'),
        ),
        migrations.AlterField(
            model_name='company',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Létrehozva'),
        ),
        migrations.AlterField(
            model_name='company',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='Módosítva'),
        ),
        migrations.AlterField(
            model_name='invoice',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Létrehozva'),
        ),
        migrations.AlterField(
            model_name='invoice',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='Módosítva'),
        ),
        migrations.AlterField(
            model_name='invoicelineitem',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Létrehozva'),
        ),
        migrations.AlterField(
            model_name='invoicesynclog',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Létrehozva'),
        ),
        migrations.AlterField(
            model_name='templatebeneficiary',
            name='is_active',
            field=models.BooleanField(default=True, verbose_name='Aktív'),
        ),
        migrations.AlterField(
            model_name='transfer',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Létrehozva'),
        ),
        migrations.AlterField(
            model_name='transfer',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='Módosítva'),
        ),
        migrations.AlterField(
            model_name='transferbatch',
            name='company',
            field=models.ForeignKey(default=4, help_text='A modell tulajdonosa', on_delete=django.db.models.deletion.CASCADE, to='bank_transfers.company', verbose_name='Cég'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='transferbatch',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Létrehozva'),
        ),
        migrations.AlterField(
            model_name='transfertemplate',
            name='company',
            field=models.ForeignKey(default=4, help_text='A modell tulajdonosa', on_delete=django.db.models.deletion.CASCADE, to='bank_transfers.company', verbose_name='Cég'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='transfertemplate',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Létrehozva'),
        ),
        migrations.AlterField(
            model_name='transfertemplate',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='Módosítva'),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Létrehozva'),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='Módosítva'),
        ),
    ]
