# Generated by Django 4.2.7 on 2025-08-25 11:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('bank_transfers', '0021_invoicelineitem_updated_at_invoicesynclog_updated_at_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='invoice',
            name='storno_of',
            field=models.ForeignKey(blank=True, help_text='A STORNO számla által érvénytelenített eredeti számla', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='storno_invoices', to='bank_transfers.invoice', verbose_name='Eredeti számla (amit ez a storno érvénytelenít)'),
        ),
    ]
