# Generated by Django 4.2.7 on 2025-08-25 11:08

from django.db import migrations


def populate_storno_relationships(apps, schema_editor):
    """
    Populate storno_of relationships based on existing original_invoice_number field.
    """
    Invoice = apps.get_model('bank_transfers', 'Invoice')
    
    # Find all STORNO invoices that have original_invoice_number
    storno_invoices = Invoice.objects.filter(
        invoice_operation='STORNO',
        original_invoice_number__isnull=False
    )
    
    populated_count = 0
    for storno_invoice in storno_invoices:
        try:
            # Find the original invoice within the same company
            original_invoice = Invoice.objects.get(
                company=storno_invoice.company,
                nav_invoice_number=storno_invoice.original_invoice_number
            )
            
            # Set the ForeignKey relationship
            storno_invoice.storno_of = original_invoice
            storno_invoice.save(update_fields=['storno_of'])
            populated_count += 1
            
        except Invoice.DoesNotExist:
            # Original invoice not found, skip this STORNO
            print(f"Warning: Original invoice {storno_invoice.original_invoice_number} not found for STORNO {storno_invoice.nav_invoice_number}")
            continue
        except Invoice.MultipleObjectsReturned:
            # Multiple invoices with same number, skip for safety
            print(f"Warning: Multiple invoices found for {storno_invoice.original_invoice_number}, skipping STORNO {storno_invoice.nav_invoice_number}")
            continue
    
    print(f"Populated {populated_count} STORNO relationships")


def reverse_populate_storno_relationships(apps, schema_editor):
    """
    Reverse operation: clear all storno_of relationships.
    """
    Invoice = apps.get_model('bank_transfers', 'Invoice')
    Invoice.objects.filter(storno_of__isnull=False).update(storno_of=None)


class Migration(migrations.Migration):

    dependencies = [
        ('bank_transfers', '0022_invoice_storno_of'),
    ]

    operations = [
        migrations.RunPython(
            populate_storno_relationships,
            reverse_populate_storno_relationships
        ),
    ]
