# Generated by Django 4.2.7 on 2025-08-26 15:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bank_transfers', '0023_populate_storno_relationships'),
    ]

    operations = [
        migrations.AddField(
            model_name='transferbatch',
            name='batch_format',
            field=models.CharField(choices=[('XML', 'SEPA XML'), ('KH_CSV', 'KH Bank CSV')], default='XML', max_length=10, verbose_name='Fájlformátum'),
        ),
        migrations.AlterField(
            model_name='transferbatch',
            name='used_in_bank',
            field=models.BooleanField(default=False, help_text='Jelzi, hogy a fájl fel lett-e töltve az internetbankba', verbose_name='Felhasználva a bankban'),
        ),
        migrations.AlterField(
            model_name='transferbatch',
            name='xml_generated_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Fájl generálás ideje'),
        ),
    ]
