# Generated by Django 4.2.7 on 2025-08-28 17:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bank_transfers', '0024_add_batch_format_field'),
    ]

    operations = [
        migrations.AddField(
            model_name='invoice',
            name='customer_bank_account_number',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Vevő bankszámlaszáma'),
        ),
        migrations.AddField(
            model_name='invoice',
            name='supplier_bank_account_number',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Szállító bankszámlaszáma'),
        ),
    ]
