# Generated by Django 4.2.7 on 2025-08-30 15:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bank_transfers', '0025_add_bank_account_fields'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='navconfiguration',
            name='last_sync_timestamp',
        ),
        migrations.RemoveField(
            model_name='navconfiguration',
            name='sync_frequency_hours',
        ),
    ]
