# Generated by Django 4.2.7 on 2025-08-30 18:53

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('bank_transfers', '0026_remove_unused_nav_sync_fields'),
    ]

    operations = [
        migrations.CreateModel(
            name='CompanyFeature',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Létrehozva')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Módosítva')),
                ('is_enabled', models.BooleanField(default=False, help_text='Whether this feature is active for the company', verbose_name='Engedélyezett')),
                ('config_data', models.JSONField(blank=True, help_text='Company-specific configuration for this feature', null=True, verbose_name='Konfigurációs adatok')),
                ('enabled_at', models.DateTimeField(blank=True, help_text='When this feature was first enabled', null=True, verbose_name='Engedélyezve ekkor')),
            ],
            options={
                'verbose_name': 'Cég feature',
                'verbose_name_plural': 'Cég feature-ök',
                'ordering': ['company__name', 'feature_template__category', 'feature_template__display_name'],
            },
        ),
        migrations.CreateModel(
            name='FeatureTemplate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Létrehozva')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Módosítva')),
                ('feature_code', models.CharField(help_text="Unique identifier for the feature (e.g., 'EXPORT_XML_SEPA')", max_length=50, unique=True, verbose_name='Feature kód')),
                ('display_name', models.CharField(help_text='Human-readable name shown in UI', max_length=100, verbose_name='Megjelenített név')),
                ('description', models.TextField(blank=True, help_text='Detailed description of what this feature enables', verbose_name='Leírás')),
                ('category', models.CharField(choices=[('EXPORT', 'Export Features'), ('SYNC', 'Synchronization Features'), ('TRACKING', 'Tracking & Management Features'), ('REPORTING', 'Reporting Features'), ('INTEGRATION', 'Integration Features'), ('GENERAL', 'General Features')], default='GENERAL', max_length=20, verbose_name='Kategória')),
                ('default_enabled', models.BooleanField(default=False, help_text='Whether this feature should be enabled for new companies', verbose_name='Alapértelmezetten engedélyezett')),
                ('config_schema', models.JSONField(blank=True, help_text='JSON schema for feature-specific configuration validation', null=True, verbose_name='Konfigurációs séma')),
                ('is_system_critical', models.BooleanField(default=False, help_text='Critical features that cannot be disabled', verbose_name='Rendszerkritikus')),
            ],
            options={
                'verbose_name': 'Feature sablon',
                'verbose_name_plural': 'Feature sablonok',
                'ordering': ['category', 'display_name'],
            },
        ),
        migrations.AddField(
            model_name='companyuser',
            name='custom_permissions',
            field=models.JSONField(blank=True, help_text='JSON array of additional feature codes this user can access beyond their role', null=True, verbose_name='Egyedi jogosultságok'),
        ),
        migrations.AddField(
            model_name='companyuser',
            name='permission_restrictions',
            field=models.JSONField(blank=True, help_text='JSON array of feature codes this user is explicitly denied access to', null=True, verbose_name='Jogosultság korlátozások'),
        ),
        migrations.AlterField(
            model_name='companyuser',
            name='role',
            field=models.CharField(choices=[('ADMIN', 'Cég adminisztrátor'), ('FINANCIAL', 'Pénzügyi munkatárs'), ('ACCOUNTANT', 'Könyvelő'), ('USER', 'Alapfelhasználó')], default='USER', max_length=15, verbose_name='Szerepkör'),
        ),
        migrations.AddIndex(
            model_name='companyuser',
            index=models.Index(fields=['company', 'role'], name='bank_transf_company_109fb2_idx'),
        ),
        migrations.AddIndex(
            model_name='companyuser',
            index=models.Index(fields=['user', 'company'], name='bank_transf_user_id_74ce99_idx'),
        ),
        migrations.AddIndex(
            model_name='featuretemplate',
            index=models.Index(fields=['category'], name='bank_transf_categor_f3a5c6_idx'),
        ),
        migrations.AddIndex(
            model_name='featuretemplate',
            index=models.Index(fields=['feature_code'], name='bank_transf_feature_4d1c62_idx'),
        ),
        migrations.AddField(
            model_name='companyfeature',
            name='company',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='features', to='bank_transfers.company', verbose_name='Cég'),
        ),
        migrations.AddField(
            model_name='companyfeature',
            name='enabled_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='enabled_features', to=settings.AUTH_USER_MODEL, verbose_name='Engedélyezte'),
        ),
        migrations.AddField(
            model_name='companyfeature',
            name='feature_template',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='company_instances', to='bank_transfers.featuretemplate', verbose_name='Feature sablon'),
        ),
        migrations.AddIndex(
            model_name='companyfeature',
            index=models.Index(fields=['company', 'is_enabled'], name='bank_transf_company_793982_idx'),
        ),
        migrations.AddIndex(
            model_name='companyfeature',
            index=models.Index(fields=['feature_template', 'is_enabled'], name='bank_transf_feature_2c5f18_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='companyfeature',
            unique_together={('company', 'feature_template')},
        ),
    ]
