# Generated by Django 4.2.7 on 2025-08-31 15:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bank_transfers', '0028_initialize_default_features'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='company',
            name='address',
        ),
        migrations.RemoveField(
            model_name='company',
            name='email',
        ),
        migrations.RemoveField(
            model_name='company',
            name='phone',
        ),
    ]
