# Generated by Django 4.2.7 on 2025-09-05 04:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bank_transfers', '0029_remove_company_address_remove_company_email_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='invoice',
            name='auto_marked_paid',
            field=models.BooleanField(default=False, verbose_name='Automatikusan fizetettnek jelölve'),
        ),
    ]
