# Generated by Django 4.2.7 on 2025-09-03 18:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('bank_transfers', '0029_remove_company_address_remove_company_email_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='invoice',
            name='auto_marked_paid',
            field=models.BooleanField(default=False, help_text='Igaz, ha automatikusan lett megjelölve fizetettként köteg feldolgozáskor', verbose_name='Automatikusan jelölve'),
        ),
        migrations.AddField(
            model_name='invoice',
            name='payment_status',
            field=models.CharField(choices=[('UNPAID', 'Nem fizetve'), ('PAID', 'Kifizetve'), ('OVERDUE', 'Lejárt')], default='UNPAID', help_text='A számla aktuális fizetési státusza', max_length=20, verbose_name='Fizetési állapot'),
        ),
        migrations.AddField(
            model_name='invoice',
            name='payment_status_date',
            field=models.DateField(blank=True, help_text='A számla kifizetésének dátuma (PAID státusz esetén)', null=True, verbose_name='Fizetési állapot dátuma'),
        ),
        migrations.AddField(
            model_name='transfer',
            name='nav_invoice',
            field=models.ForeignKey(blank=True, help_text='A NAV számla, amelyből ez az átutalás generálva lett (opcionális)', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='generated_transfers', to='bank_transfers.invoice', verbose_name='NAV számla'),
        ),
    ]
