# Generated by Django 4.2.7 on 2025-09-04 04:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bank_transfers', '0031_add_prepared_payment_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='invoice',
            name='payment_status',
            field=models.CharField(choices=[('UNPAID', 'Nem fizetve'), ('PREPARED', 'Előkészítve'), ('PAID', 'Kifizetve')], default='UNPAID', help_text='A számla aktuális fizetési státusza', max_length=20, verbose_name='Fizetési állapot'),
        ),
    ]
