# Generated by Django 4.2.7 on 2025-09-05 17:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bank_transfers', '0030_add_nav_invoice_payment_tracking'),
        ('bank_transfers', '0032_remove_overdue_status'),
    ]

    operations = [
    ]
