# Generated by Django 4.2.7 on 2025-09-05 19:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('bank_transfers', '0033_merge_20250905_1937'),
    ]

    operations = [
        migrations.AlterField(
            model_name='invoice',
            name='payment_status',
            field=models.CharField(choices=[('UNPAID', 'Fizetésre vár'), ('PREPARED', 'Előkészítve'), ('PAID', 'Kifizetve')], default='UNPAID', max_length=10, verbose_name='Fizetési állapot'),
        ),
        migrations.CreateModel(
            name='TrustedPartner',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Létrehozva')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Módosítva')),
                ('partner_name', models.CharField(max_length=200, verbose_name='Partner neve')),
                ('tax_number', models.CharField(max_length=20, verbose_name='Adószám')),
                ('is_active', models.BooleanField(default=True, verbose_name='Aktív')),
                ('auto_pay', models.BooleanField(default=True, verbose_name='Automatikus fizetés')),
                ('notes', models.TextField(blank=True, verbose_name='Megjegyzések')),
                ('invoice_count', models.IntegerField(default=0, verbose_name='Számlák száma')),
                ('last_invoice_date', models.DateField(blank=True, null=True, verbose_name='Utolsó számla dátuma')),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='trusted_partners', to='bank_transfers.company')),
            ],
            options={
                'verbose_name': 'Megbízható partner',
                'verbose_name_plural': 'Megbízható partnerek',
                'ordering': ['partner_name'],
                'indexes': [models.Index(fields=['company', 'tax_number'], name='bank_transf_company_5c0522_idx'), models.Index(fields=['is_active', 'auto_pay'], name='bank_transf_is_acti_fc393a_idx')],
                'unique_together': {('company', 'tax_number')},
            },
        ),
    ]
