# Generated by Django 4.2.7 on 2025-09-08 17:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bank_transfers', '0034_alter_invoice_payment_status_trustedpartner'),
    ]

    operations = [
        migrations.AddField(
            model_name='beneficiary',
            name='vat_number',
            field=models.CharField(blank=True, help_text='Magyar személyi adószám vagy adóazonosító szám (pl. 8450782546)', max_length=20, null=True, verbose_name='Adószám'),
        ),
        migrations.AddIndex(
            model_name='beneficiary',
            index=models.Index(fields=['vat_number'], name='bank_transf_vat_num_2c8389_idx'),
        ),
    ]
