# Generated by Django 4.2.7 on 2025-09-08 18:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bank_transfers', '0035_add_vat_number_to_beneficiary'),
    ]

    operations = [
        migrations.AlterField(
            model_name='beneficiary',
            name='account_number',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Számlaszám'),
        ),
    ]
