# Generated by Django 4.2.7 on 2025-09-23 16:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bank_transfers', '0036_make_account_number_nullable'),
    ]

    operations = [
        migrations.AddField(
            model_name='beneficiary',
            name='tax_number',
            field=models.CharField(blank=True, help_text='Magyar céges adószám első 8 számjegye (pl. 12345678)', max_length=8, null=True, verbose_name='Céges adószám'),
        ),
        migrations.AlterField(
            model_name='beneficiary',
            name='vat_number',
            field=models.CharField(blank=True, help_text='Magyar személyi adóazonosító jel (pl. 8440961790)', max_length=20, null=True, verbose_name='Adóazonosító jel'),
        ),
        migrations.AddIndex(
            model_name='beneficiary',
            index=models.Index(fields=['tax_number'], name='bank_transf_tax_num_011694_idx'),
        ),
    ]
