# Generated by Django 4.2.7 on 2025-10-18 21:08

from decimal import Decimal
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('bank_transfers', '0038_add_exchange_rate_models'),
    ]

    operations = [
        migrations.CreateModel(
            name='BankStatement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Létrehozva')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Módosítva')),
                ('bank_code', models.CharField(db_index=True, help_text='Bank identifier: GRANIT, OTP, KH, CIB, ERSTE', max_length=20, verbose_name='Bank kód')),
                ('bank_name', models.CharField(max_length=100, verbose_name='Bank neve')),
                ('bank_bic', models.CharField(blank=True, max_length=11, verbose_name='BIC kód')),
                ('account_number', models.CharField(db_index=True, max_length=50, verbose_name='Számlaszám')),
                ('account_iban', models.CharField(blank=True, max_length=34, verbose_name='IBAN')),
                ('statement_period_from', models.DateField(verbose_name='Kivonat időszak kezdete')),
                ('statement_period_to', models.DateField(verbose_name='Kivonat időszak vége')),
                ('statement_number', models.CharField(blank=True, max_length=50, verbose_name='Kivonat száma')),
                ('opening_balance', models.DecimalField(decimal_places=2, max_digits=15, verbose_name='Nyitó egyenleg')),
                ('closing_balance', models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True, verbose_name='Záró egyenleg')),
                ('file_name', models.CharField(max_length=255, verbose_name='Fájlnév')),
                ('file_hash', models.CharField(db_index=True, max_length=64, verbose_name='Fájl hash (SHA256)')),
                ('file_size', models.IntegerField(verbose_name='Fájl méret (byte)')),
                ('file_path', models.CharField(max_length=500, verbose_name='Fájl elérési út')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True, verbose_name='Feltöltés ideje')),
                ('status', models.CharField(choices=[('UPLOADED', 'Feltöltve'), ('PARSING', 'Feldolgozás alatt'), ('PARSED', 'Feldolgozva'), ('ERROR', 'Hiba')], db_index=True, default='UPLOADED', max_length=20, verbose_name='Státusz')),
                ('total_transactions', models.IntegerField(default=0, verbose_name='Összes tranzakció')),
                ('credit_count', models.IntegerField(default=0, verbose_name='Jóváírások száma')),
                ('debit_count', models.IntegerField(default=0, verbose_name='Terhelések száma')),
                ('total_credits', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=15, verbose_name='Összesen jóváírva')),
                ('total_debits', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=15, verbose_name='Összesen terhelve')),
                ('matched_count', models.IntegerField(default=0, verbose_name='Párosított tranzakciók')),
                ('parse_error', models.TextField(blank=True, null=True, verbose_name='Feldolgozási hiba')),
                ('parse_warnings', models.JSONField(blank=True, default=list, verbose_name='Figyelmeztetések')),
                ('raw_metadata', models.JSONField(blank=True, default=dict, verbose_name='Nyers metaadatok')),
            ],
            options={
                'verbose_name': 'Bankszámlakivonat',
                'verbose_name_plural': 'Bankszámlakivonatok',
                'ordering': ['-statement_period_to', '-uploaded_at'],
            },
        ),
        migrations.CreateModel(
            name='BankTransaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Létrehozva')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Módosítva')),
                ('transaction_type', models.CharField(choices=[('AFR_CREDIT', 'AFR jóváírás (Incoming instant payment)'), ('AFR_DEBIT', 'AFR terhelés (Outgoing instant payment)'), ('TRANSFER_CREDIT', 'Átutalás jóváírás (Incoming transfer)'), ('TRANSFER_DEBIT', 'Átutalás terhelés (Outgoing transfer)'), ('POS_PURCHASE', 'POS vásárlás (Card purchase)'), ('ATM_WITHDRAWAL', 'ATM készpénzfelvétel (Cash withdrawal)'), ('BANK_FEE', 'Banki jutalék/költség (Bank fee)'), ('INTEREST_CREDIT', 'Kamatjóváírás (Interest credit)'), ('INTEREST_DEBIT', 'Kamatköltség (Interest charge)'), ('CORRECTION', 'Helyesbítés/Sztornó (Correction)'), ('OTHER', 'Egyéb tranzakció (Other)')], db_index=True, max_length=30, verbose_name='Tranzakció típusa')),
                ('booking_date', models.DateField(db_index=True, verbose_name='Könyvelés dátuma')),
                ('value_date', models.DateField(db_index=True, verbose_name='Értéknap')),
                ('amount', models.DecimalField(db_index=True, decimal_places=2, help_text='Negative for debit, positive for credit', max_digits=15, verbose_name='Összeg')),
                ('currency', models.CharField(default='HUF', max_length=3, verbose_name='Deviza')),
                ('description', models.TextField(verbose_name='Leírás')),
                ('short_description', models.CharField(blank=True, max_length=200, verbose_name='Rövid leírás')),
                ('payment_id', models.CharField(blank=True, db_index=True, max_length=100, verbose_name='Fizetési azonosító')),
                ('transaction_id', models.CharField(blank=True, max_length=100, verbose_name='Tranzakció azonosító')),
                ('payer_name', models.CharField(blank=True, db_index=True, max_length=200, verbose_name='Fizető fél neve')),
                ('payer_iban', models.CharField(blank=True, max_length=34, verbose_name='Fizető fél IBAN')),
                ('payer_account_number', models.CharField(blank=True, max_length=50, verbose_name='Fizető fél számlaszáma')),
                ('payer_bic', models.CharField(blank=True, max_length=11, verbose_name='Fizető fél BIC')),
                ('beneficiary_name', models.CharField(blank=True, db_index=True, max_length=200, verbose_name='Kedvezményezett neve')),
                ('beneficiary_iban', models.CharField(blank=True, max_length=34, verbose_name='Kedvezményezett IBAN')),
                ('beneficiary_account_number', models.CharField(blank=True, max_length=50, verbose_name='Kedvezményezett számlaszáma')),
                ('reference', models.CharField(blank=True, help_text='Nem strukturált közlemény - critical for invoice matching', max_length=500, verbose_name='Közlemény')),
                ('card_number', models.CharField(blank=True, max_length=20, verbose_name='Kártya szám (maszkolva)')),
                ('merchant_name', models.CharField(blank=True, max_length=200, verbose_name='Kereskedő neve')),
                ('merchant_location', models.CharField(blank=True, max_length=100, verbose_name='Kereskedő helye')),
                ('original_amount', models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True, verbose_name='Eredeti összeg (FX)')),
                ('original_currency', models.CharField(blank=True, max_length=3, verbose_name='Eredeti deviza (FX)')),
                ('match_confidence', models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='0.00 to 1.00', max_digits=3, verbose_name='Párosítás megbízhatósága')),
                ('match_method', models.CharField(blank=True, choices=[('REFERENCE_EXACT', 'Közlemény alapján (pontos)'), ('AMOUNT_IBAN', 'Összeg + IBAN alapján'), ('FUZZY_NAME', 'Összeg + név hasonlóság alapján'), ('MANUAL', 'Manuális párosítás')], max_length=50, verbose_name='Párosítás módja')),
                ('match_notes', models.TextField(blank=True, verbose_name='Párosítási megjegyzések')),
                ('matched_at', models.DateTimeField(blank=True, null=True, verbose_name='Párosítás ideje')),
                ('is_extra_cost', models.BooleanField(db_index=True, default=False, verbose_name='Extra költség')),
                ('extra_cost_category', models.CharField(blank=True, choices=[('BANK_FEE', 'Banki költség'), ('CARD_PURCHASE', 'Kártyás vásárlás'), ('INTEREST', 'Kamat'), ('TAX_DUTY', 'Adó/illeték'), ('CASH_WITHDRAWAL', 'Készpénzfelvétel'), ('OTHER', 'Egyéb költség')], max_length=50, verbose_name='Költség kategória')),
                ('raw_data', models.JSONField(blank=True, default=dict, verbose_name='Nyers adatok')),
            ],
            options={
                'verbose_name': 'Banki tranzakció',
                'verbose_name_plural': 'Banki tranzakciók',
                'ordering': ['-booking_date', '-value_date'],
            },
        ),
        migrations.CreateModel(
            name='OtherCost',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Létrehozva')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Módosítva')),
                ('category', models.CharField(choices=[('BANK_FEE', 'Banki költség'), ('CARD_PURCHASE', 'Kártyás vásárlás'), ('INTEREST', 'Kamat'), ('TAX_DUTY', 'Adó/illeték'), ('CASH_WITHDRAWAL', 'Készpénzfelvétel'), ('SUBSCRIPTION', 'Előfizetés'), ('UTILITY', 'Közüzem'), ('FUEL', 'Üzemanyag'), ('TRAVEL', 'Utazás'), ('OFFICE', 'Iroda/irodaszer'), ('OTHER', 'Egyéb')], max_length=50, verbose_name='Kategória')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=15, verbose_name='Összeg')),
                ('currency', models.CharField(default='HUF', max_length=3, verbose_name='Deviza')),
                ('date', models.DateField(verbose_name='Dátum')),
                ('description', models.TextField(verbose_name='Leírás')),
                ('notes', models.TextField(blank=True, verbose_name='Megjegyzések')),
                ('tags', models.JSONField(blank=True, default=list, help_text="E.g., ['fuel', 'travel', 'office']", verbose_name='Címkék')),
            ],
            options={
                'verbose_name': 'Egyéb költség',
                'verbose_name_plural': 'Egyéb költségek',
                'ordering': ['-date'],
            },
        ),
        migrations.RenameIndex(
            model_name='exchangerate',
            new_name='bank_transf_rate_da_60e1ed_idx',
            old_name='bank_transf_rate_da_7f3e8a_idx',
        ),
        migrations.RenameIndex(
            model_name='exchangerate',
            new_name='bank_transf_rate_da_833c8f_idx',
            old_name='bank_transf_rate_da_e1b2f5_idx',
        ),
        migrations.RenameIndex(
            model_name='exchangerate',
            new_name='bank_transf_currenc_b9acf9_idx',
            old_name='bank_transf_currenc_a5c7d2_idx',
        ),
        migrations.RenameIndex(
            model_name='exchangeratesynclog',
            new_name='bank_transf_sync_st_97cd79_idx',
            old_name='bank_transf_sync_st_4b9c6d_idx',
        ),
        migrations.RenameIndex(
            model_name='exchangeratesynclog',
            new_name='bank_transf_sync_st_41140e_idx',
            old_name='bank_transf_sync_st_2e8a1f_idx',
        ),
        migrations.AlterField(
            model_name='exchangerate',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Létrehozva'),
        ),
        migrations.AlterField(
            model_name='exchangerate',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='Módosítva'),
        ),
        migrations.AlterField(
            model_name='exchangeratesynclog',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Létrehozva'),
        ),
        migrations.AlterField(
            model_name='exchangeratesynclog',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='Módosítva'),
        ),
        migrations.AddField(
            model_name='othercost',
            name='bank_transaction',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='other_cost_detail', to='bank_transfers.banktransaction', verbose_name='Banki tranzakció'),
        ),
        migrations.AddField(
            model_name='othercost',
            name='company',
            field=models.ForeignKey(help_text='A modell tulajdonosa', on_delete=django.db.models.deletion.CASCADE, to='bank_transfers.company', verbose_name='Cég'),
        ),
        migrations.AddField(
            model_name='othercost',
            name='created_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Létrehozta'),
        ),
        migrations.AddField(
            model_name='banktransaction',
            name='bank_statement',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transactions', to='bank_transfers.bankstatement', verbose_name='Bankszámlakivonat'),
        ),
        migrations.AddField(
            model_name='banktransaction',
            name='company',
            field=models.ForeignKey(help_text='A modell tulajdonosa', on_delete=django.db.models.deletion.CASCADE, to='bank_transfers.company', verbose_name='Cég'),
        ),
        migrations.AddField(
            model_name='banktransaction',
            name='matched_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='matched_transactions', to=settings.AUTH_USER_MODEL, verbose_name='Párosította'),
        ),
        migrations.AddField(
            model_name='banktransaction',
            name='matched_invoice',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='bank_transactions', to='bank_transfers.invoice', verbose_name='Párosított számla'),
        ),
        migrations.AddField(
            model_name='bankstatement',
            name='company',
            field=models.ForeignKey(help_text='A modell tulajdonosa', on_delete=django.db.models.deletion.CASCADE, to='bank_transfers.company', verbose_name='Cég'),
        ),
        migrations.AddField(
            model_name='bankstatement',
            name='uploaded_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='uploaded_statements', to=settings.AUTH_USER_MODEL, verbose_name='Feltöltő'),
        ),
        migrations.AddIndex(
            model_name='banktransaction',
            index=models.Index(fields=['bank_statement', 'booking_date'], name='bank_transf_bank_st_1305d0_idx'),
        ),
        migrations.AddIndex(
            model_name='banktransaction',
            index=models.Index(fields=['company', 'booking_date'], name='bank_transf_company_573d22_idx'),
        ),
        migrations.AddIndex(
            model_name='banktransaction',
            index=models.Index(fields=['company', 'transaction_type', 'booking_date'], name='bank_transf_company_9e68a8_idx'),
        ),
        migrations.AddIndex(
            model_name='banktransaction',
            index=models.Index(fields=['amount', 'currency'], name='bank_transf_amount_4c2227_idx'),
        ),
        migrations.AddIndex(
            model_name='banktransaction',
            index=models.Index(fields=['matched_invoice'], name='bank_transf_matched_cdfcba_idx'),
        ),
        migrations.AddIndex(
            model_name='banktransaction',
            index=models.Index(fields=['payment_id'], name='bank_transf_payment_362a90_idx'),
        ),
        migrations.AddIndex(
            model_name='banktransaction',
            index=models.Index(fields=['reference'], name='bank_transf_referen_12bbeb_idx'),
        ),
        migrations.AddIndex(
            model_name='banktransaction',
            index=models.Index(fields=['is_extra_cost', 'extra_cost_category'], name='bank_transf_is_extr_aa4197_idx'),
        ),
        migrations.AddIndex(
            model_name='bankstatement',
            index=models.Index(fields=['company', 'bank_code', 'account_number'], name='bank_transf_company_69634d_idx'),
        ),
        migrations.AddIndex(
            model_name='bankstatement',
            index=models.Index(fields=['company', 'status'], name='bank_transf_company_f723ec_idx'),
        ),
        migrations.AddIndex(
            model_name='bankstatement',
            index=models.Index(fields=['company', 'statement_period_to'], name='bank_transf_company_fd7a5f_idx'),
        ),
        migrations.AddIndex(
            model_name='bankstatement',
            index=models.Index(fields=['uploaded_at'], name='bank_transf_uploade_7019e1_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='bankstatement',
            unique_together={('company', 'file_hash'), ('company', 'bank_code', 'account_number', 'statement_period_from', 'statement_period_to')},
        ),
    ]
