# Generated by Django 4.2.7 on 2025-10-19 06:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bank_transfers', '0039_add_bank_statement_models'),
    ]

    operations = [
        migrations.AddField(
            model_name='banktransaction',
            name='beneficiary_bic',
            field=models.CharField(blank=True, max_length=11, verbose_name='Kedvezményezett BIC'),
        ),
        migrations.AddField(
            model_name='banktransaction',
            name='fee_amount',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Transaction fee (Előjegyzett jutalék)', max_digits=15, null=True, verbose_name='Jutalék összege'),
        ),
        migrations.AddField(
            model_name='banktransaction',
            name='partner_id',
            field=models.CharField(blank=True, help_text='End-to-end ID between partners', max_length=100, verbose_name='Partnerek közti azonosító'),
        ),
        migrations.AddField(
            model_name='banktransaction',
            name='transaction_type_code',
            field=models.CharField(blank=True, help_text='Bank-specific transaction type code (e.g., 001-00)', max_length=20, verbose_name='Tranzakció típus kód'),
        ),
    ]
