# Generated by Django 4.2.7 on 2025-10-19 11:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('bank_transfers', '0040_add_transaction_fields'),
    ]

    operations = [
        migrations.AddField(
            model_name='banktransaction',
            name='matched_reimbursement',
            field=models.ForeignKey(blank=True, help_text='Offsetting transaction (e.g., POS purchase + personal transfer)', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reimbursement_pair', to='bank_transfers.banktransaction', verbose_name='Párosított ellentétel'),
        ),
        migrations.AddField(
            model_name='banktransaction',
            name='matched_transfer',
            field=models.ForeignKey(blank=True, help_text='Transfer from executed TransferBatch (used_in_bank=True)', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='bank_transactions', to='bank_transfers.transfer', verbose_name='Párosított átutalás'),
        ),
        migrations.AlterField(
            model_name='banktransaction',
            name='match_method',
            field=models.CharField(blank=True, choices=[('REFERENCE_EXACT', 'Közlemény alapján (pontos)'), ('AMOUNT_IBAN', 'Összeg + IBAN alapján'), ('FUZZY_NAME', 'Összeg + név hasonlóság alapján'), ('TRANSFER_EXACT', 'Átutalási köteg alapján'), ('REIMBURSEMENT_PAIR', 'Ellentételezés (személyes visszafizetés)'), ('MANUAL', 'Manuális párosítás')], max_length=50, verbose_name='Párosítás módja'),
        ),
    ]
