# Generated by Django 4.2.7 on 2025-10-21 05:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bank_transfers', '0041_add_transfer_reimbursement_matching'),
    ]

    operations = [
        migrations.AlterField(
            model_name='banktransaction',
            name='merchant_location',
            field=models.CharField(blank=True, max_length=200, verbose_name='Kereskedő helye'),
        ),
    ]
