# Generated by Django 4.2.7 on 2025-10-21 16:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bank_transfers', '0042_increase_merchant_location_length'),
    ]

    operations = [
        migrations.AddField(
            model_name='banktransaction',
            name='exchange_rate',
            field=models.DecimalField(blank=True, decimal_places=6, help_text='Exchange rate used for currency conversion (6 decimal precision)', max_digits=15, null=True, verbose_name='Átváltási árfolyam'),
        ),
    ]
