# Generated by Django 4.2.7 on 2025-10-21 17:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bank_transfers', '0043_add_exchange_rate_field'),
    ]

    operations = [
        migrations.AlterField(
            model_name='banktransaction',
            name='transaction_type_code',
            field=models.CharField(blank=True, help_text='Bank-specific transaction type code (e.g., 001-00)', max_length=100, verbose_name='Tranzakció típus kód'),
        ),
    ]
