# Generated by Django 4.2.7 on 2025-10-25 12:30

from django.db import migrations


def normalize_transaction_types(apps, schema_editor):
    """
    Convert simplified transaction types to detailed types with direction.

    Maps:
    - TRANSFER → TRANSFER_CREDIT (if amount > 0) or TRANSFER_DEBIT (if amount < 0)
    - POS → POS_PURCHASE
    - FEE → BANK_FEE
    - INTEREST → INTEREST_CREDIT (if amount > 0) or INTEREST_DEBIT (if amount < 0)

    Leaves already-detailed types unchanged:
    - AFR_CREDIT, AFR_DEBIT, TRANSFER_CREDIT, TRANSFER_DEBIT, POS_PURCHASE, etc.
    """
    BankTransaction = apps.get_model('bank_transfers', 'BankTransaction')

    # Process transactions in batches
    batch_size = 500
    updated_count = 0

    # Get transactions with simplified types
    simplified_types = ['TRANSFER', 'POS', 'FEE', 'INTEREST']
    transactions = BankTransaction.objects.filter(transaction_type__in=simplified_types)

    total = transactions.count()
    print(f"Found {total} transactions to normalize...")

    for i in range(0, total, batch_size):
        batch = list(transactions[i:i + batch_size])

        for transaction in batch:
            old_type = transaction.transaction_type
            amount = transaction.amount
            is_credit = amount > 0

            # Map to detailed type
            if old_type == 'TRANSFER':
                transaction.transaction_type = 'TRANSFER_CREDIT' if is_credit else 'TRANSFER_DEBIT'
            elif old_type == 'POS':
                transaction.transaction_type = 'POS_PURCHASE'
            elif old_type == 'FEE':
                transaction.transaction_type = 'BANK_FEE'
            elif old_type == 'INTEREST':
                transaction.transaction_type = 'INTEREST_CREDIT' if is_credit else 'INTEREST_DEBIT'

        # Bulk update batch
        BankTransaction.objects.bulk_update(batch, ['transaction_type'])
        updated_count += len(batch)
        print(f"Normalized {updated_count}/{total} transactions...")

    print(f"✓ Normalized {updated_count} transaction types successfully")


def reverse_normalize(apps, schema_editor):
    """
    Reverse migration: Convert detailed types back to simplified types.

    Maps:
    - TRANSFER_CREDIT, TRANSFER_DEBIT → TRANSFER
    - AFR_CREDIT, AFR_DEBIT → TRANSFER
    - POS_PURCHASE → POS
    - BANK_FEE → FEE
    - INTEREST_CREDIT, INTEREST_DEBIT → INTEREST
    """
    BankTransaction = apps.get_model('bank_transfers', 'BankTransaction')

    batch_size = 500
    updated_count = 0

    # Get transactions with detailed types
    detailed_types = [
        'TRANSFER_CREDIT', 'TRANSFER_DEBIT',
        'AFR_CREDIT', 'AFR_DEBIT',
        'POS_PURCHASE',
        'BANK_FEE',
        'INTEREST_CREDIT', 'INTEREST_DEBIT'
    ]
    transactions = BankTransaction.objects.filter(transaction_type__in=detailed_types)

    total = transactions.count()
    print(f"Found {total} transactions to reverse...")

    for i in range(0, total, batch_size):
        batch = list(transactions[i:i + batch_size])

        for transaction in batch:
            old_type = transaction.transaction_type

            # Map to simplified type
            if old_type in ('TRANSFER_CREDIT', 'TRANSFER_DEBIT', 'AFR_CREDIT', 'AFR_DEBIT'):
                transaction.transaction_type = 'TRANSFER'
            elif old_type == 'POS_PURCHASE':
                transaction.transaction_type = 'POS'
            elif old_type == 'BANK_FEE':
                transaction.transaction_type = 'FEE'
            elif old_type in ('INTEREST_CREDIT', 'INTEREST_DEBIT'):
                transaction.transaction_type = 'INTEREST'

        # Bulk update batch
        BankTransaction.objects.bulk_update(batch, ['transaction_type'])
        updated_count += len(batch)
        print(f"Reversed {updated_count}/{total} transactions...")

    print(f"✓ Reversed {updated_count} transaction types successfully")


class Migration(migrations.Migration):

    dependencies = [
        ('bank_transfers', '0044_increase_transaction_type_code_length'),
    ]

    operations = [
        migrations.RunPython(normalize_transaction_types, reverse_normalize),
    ]
