# Generated by Django 4.2.7 on 2025-10-26 20:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('bank_transfers', '0045_normalize_transaction_types'),
    ]

    operations = [
        migrations.CreateModel(
            name='BillingoInvoice',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Létrehozva')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Módosítva')),
                ('id', models.BigIntegerField(primary_key=True, serialize=False)),
                ('invoice_number', models.CharField(max_length=50, verbose_name='Számlaszám')),
                ('type', models.CharField(help_text='invoice, receipt, proforma, stb.', max_length=30, verbose_name='Típus')),
                ('correction_type', models.CharField(blank=True, max_length=30, verbose_name='Helyesbítés típusa')),
                ('cancelled', models.BooleanField(default=False, verbose_name='Sztornózott')),
                ('block_id', models.IntegerField(blank=True, null=True, verbose_name='Billingo blokk ID')),
                ('payment_status', models.CharField(help_text='paid, unpaid, overdue, stb.', max_length=30, verbose_name='Fizetési státusz')),
                ('payment_method', models.CharField(blank=True, help_text='wire_transfer, cash, stb.', max_length=30, verbose_name='Fizetési mód')),
                ('gross_total', models.DecimalField(decimal_places=2, max_digits=15, verbose_name='Bruttó összeg')),
                ('currency', models.CharField(max_length=5, verbose_name='Deviza')),
                ('conversion_rate', models.DecimalField(decimal_places=6, default=1, max_digits=10, verbose_name='Átváltási árfolyam')),
                ('invoice_date', models.DateField(verbose_name='Számla kelte')),
                ('fulfillment_date', models.DateField(blank=True, null=True, verbose_name='Teljesítés dátuma')),
                ('due_date', models.DateField(blank=True, null=True, verbose_name='Fizetési határidő')),
                ('paid_date', models.DateField(blank=True, null=True, verbose_name='Kiegyenlítés dátuma')),
                ('organization_name', models.CharField(max_length=255, verbose_name='Saját cég neve')),
                ('organization_tax_number', models.CharField(max_length=50, verbose_name='Saját adószám')),
                ('organization_bank_account_number', models.CharField(blank=True, max_length=100, verbose_name='Saját bankszámlaszám')),
                ('organization_bank_account_iban', models.CharField(blank=True, max_length=100, verbose_name='Saját IBAN')),
                ('organization_swift', models.CharField(blank=True, max_length=20, verbose_name='Saját SWIFT/BIC')),
                ('partner_id', models.BigIntegerField(blank=True, null=True, verbose_name='Partner Billingo ID')),
                ('partner_name', models.CharField(max_length=255, verbose_name='Partner neve')),
                ('partner_tax_number', models.CharField(blank=True, max_length=50, verbose_name='Partner adószáma')),
                ('partner_iban', models.CharField(blank=True, max_length=100, verbose_name='Partner IBAN')),
                ('partner_swift', models.CharField(blank=True, max_length=20, verbose_name='Partner SWIFT/BIC')),
                ('partner_account_number', models.CharField(blank=True, max_length=100, verbose_name='Partner számlaszáma')),
                ('comment', models.TextField(blank=True, verbose_name='Megjegyzés')),
                ('online_szamla_status', models.CharField(blank=True, max_length=30, verbose_name='Online Számla státusz')),
                ('last_modified', models.DateTimeField(auto_now=True, verbose_name='Utoljára módosítva')),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='billingo_invoices', to='bank_transfers.company', verbose_name='Cég')),
            ],
            options={
                'verbose_name': 'Billingo számla',
                'verbose_name_plural': 'Billingo számlák',
                'ordering': ['-invoice_date'],
            },
        ),
        migrations.CreateModel(
            name='BillingoSyncLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Létrehozva')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Módosítva')),
                ('sync_type', models.CharField(choices=[('MANUAL', 'Kézi'), ('AUTOMATIC', 'Automatikus')], max_length=20, verbose_name='Szinkronizálás típusa')),
                ('invoices_processed', models.IntegerField(default=0, verbose_name='Feldolgozott számlák')),
                ('invoices_created', models.IntegerField(default=0, verbose_name='Létrehozott számlák')),
                ('invoices_updated', models.IntegerField(default=0, verbose_name='Frissített számlák')),
                ('invoices_skipped', models.IntegerField(default=0, verbose_name='Kihagyott számlák')),
                ('items_extracted', models.IntegerField(default=0, verbose_name='Kivont tételek száma')),
                ('sync_duration_seconds', models.IntegerField(blank=True, null=True, verbose_name='Szinkronizálás időtartama (mp)')),
                ('api_calls_made', models.IntegerField(default=0, verbose_name='API hívások száma')),
                ('errors', models.TextField(blank=True, help_text='JSON array of errors', verbose_name='Hibák (JSON)')),
                ('status', models.CharField(choices=[('RUNNING', 'Fut'), ('COMPLETED', 'Befejezve'), ('FAILED', 'Sikertelen'), ('PARTIAL', 'Részben sikeres')], default='RUNNING', max_length=20, verbose_name='Státusz')),
                ('started_at', models.DateTimeField(auto_now_add=True, verbose_name='Indítva')),
                ('completed_at', models.DateTimeField(blank=True, null=True, verbose_name='Befejezve')),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='billingo_sync_logs', to='bank_transfers.company', verbose_name='Cég')),
            ],
            options={
                'verbose_name': 'Billingo szinkronizálási napló',
                'verbose_name_plural': 'Billingo szinkronizálási naplók',
                'ordering': ['-started_at'],
            },
        ),
        migrations.CreateModel(
            name='BillingoInvoiceItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Létrehozva')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Módosítva')),
                ('product_id', models.BigIntegerField(blank=True, null=True, verbose_name='Termék ID')),
                ('name', models.CharField(max_length=255, verbose_name='Megnevezés')),
                ('quantity', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Mennyiség')),
                ('unit', models.CharField(help_text='PIECE, HOUR, LITER, stb.', max_length=20, verbose_name='Mértékegység')),
                ('net_unit_price', models.DecimalField(decimal_places=2, max_digits=15, verbose_name='Nettó egységár')),
                ('net_amount', models.DecimalField(decimal_places=2, max_digits=15, verbose_name='Nettó összeg')),
                ('gross_amount', models.DecimalField(decimal_places=2, max_digits=15, verbose_name='Bruttó összeg')),
                ('vat', models.CharField(help_text='27%, 5%, 0%, stb.', max_length=10, verbose_name='ÁFA kulcs')),
                ('entitlement', models.CharField(blank=True, max_length=50, verbose_name='ÁFA jogcím')),
                ('invoice', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='bank_transfers.billingoinvoice', verbose_name='Számla')),
            ],
            options={
                'verbose_name': 'Billingo számla tétel',
                'verbose_name_plural': 'Billingo számla tételek',
                'ordering': ['invoice', 'id'],
            },
        ),
        migrations.CreateModel(
            name='CompanyBillingoSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Létrehozva')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Módosítva')),
                ('api_key', models.CharField(help_text='Titkosított Billingo API kulcs (X-API-KEY header)', max_length=255, verbose_name='API kulcs (titkosított)')),
                ('last_sync_time', models.DateTimeField(blank=True, help_text='Utolsó sikeres szinkronizálás időpontja', null=True, verbose_name='Utolsó szinkronizálás')),
                ('is_active', models.BooleanField(default=True, help_text='Engedélyezi/tiltja a szinkronizálást ennél a cégnél', verbose_name='Aktív')),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='billingo_settings', to='bank_transfers.company', verbose_name='Cég')),
            ],
            options={
                'verbose_name': 'Billingo beállítás',
                'verbose_name_plural': 'Billingo beállítások',
                'indexes': [models.Index(fields=['company'], name='bank_transf_company_1ab735_idx'), models.Index(fields=['is_active'], name='bank_transf_is_acti_86c119_idx')],
            },
        ),
        migrations.AddConstraint(
            model_name='companybillingosettings',
            constraint=models.UniqueConstraint(fields=('company',), name='unique_billingo_settings_per_company'),
        ),
        migrations.AddIndex(
            model_name='billingosynclog',
            index=models.Index(fields=['company', '-started_at'], name='bank_transf_company_4da94a_idx'),
        ),
        migrations.AddIndex(
            model_name='billingosynclog',
            index=models.Index(fields=['status'], name='bank_transf_status_677934_idx'),
        ),
        migrations.AddIndex(
            model_name='billingosynclog',
            index=models.Index(fields=['sync_type'], name='bank_transf_sync_ty_2d2c3b_idx'),
        ),
        migrations.AddIndex(
            model_name='billingoinvoiceitem',
            index=models.Index(fields=['invoice'], name='bank_transf_invoice_2e0ad3_idx'),
        ),
        migrations.AddIndex(
            model_name='billingoinvoice',
            index=models.Index(fields=['company', 'invoice_date'], name='bank_transf_company_d28487_idx'),
        ),
        migrations.AddIndex(
            model_name='billingoinvoice',
            index=models.Index(fields=['company', 'payment_status'], name='bank_transf_company_5d7a6d_idx'),
        ),
        migrations.AddIndex(
            model_name='billingoinvoice',
            index=models.Index(fields=['company', 'partner_tax_number'], name='bank_transf_company_792433_idx'),
        ),
        migrations.AddIndex(
            model_name='billingoinvoice',
            index=models.Index(fields=['invoice_number'], name='bank_transf_invoice_eb4178_idx'),
        ),
        migrations.AddIndex(
            model_name='billingoinvoice',
            index=models.Index(fields=['payment_status'], name='bank_transf_payment_de1d58_idx'),
        ),
        migrations.AddIndex(
            model_name='billingoinvoice',
            index=models.Index(fields=['invoice_date'], name='bank_transf_invoice_f31cb9_idx'),
        ),
    ]
