# Generated by Django 4.2.7 on 2025-10-27 04:19

from django.db import migrations


def add_billingo_sync_feature(apps, schema_editor):
    """Add BILLINGO_SYNC feature template"""
    FeatureTemplate = apps.get_model('bank_transfers', 'FeatureTemplate')

    feature_data = {
        'feature_code': 'BILLINGO_SYNC',
        'display_name': 'Billingo Invoice Synchronization',
        'description': 'Synchronize invoices with Billingo accounting system via API v3',
        'category': 'SYNC',
        'default_enabled': False,
        'is_system_critical': False,
    }

    # Create feature template if it doesn't exist
    FeatureTemplate.objects.get_or_create(
        feature_code=feature_data['feature_code'],
        defaults=feature_data
    )


def remove_billingo_sync_feature(apps, schema_editor):
    """Remove BILLINGO_SYNC feature template"""
    FeatureTemplate = apps.get_model('bank_transfers', 'FeatureTemplate')

    # Delete the feature template
    FeatureTemplate.objects.filter(feature_code='BILLINGO_SYNC').delete()


class Migration(migrations.Migration):

    dependencies = [
        ('bank_transfers', '0046_add_billingo_models'),
    ]

    operations = [
        migrations.RunPython(add_billingo_sync_feature, remove_billingo_sync_feature),
    ]
