# Generated by Django 4.2.7 on 2025-10-27 04:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bank_transfers', '0047_add_billingo_sync_feature'),
    ]

    operations = [
        migrations.AlterField(
            model_name='billingoinvoiceitem',
            name='entitlement',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='ÁFA jogcím'),
        ),
    ]
