# Generated by Django 4.2.7 on 2025-10-27 19:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bank_transfers', '0048_allow_null_entitlement'),
    ]

    operations = [
        migrations.AddField(
            model_name='companybillingosettings',
            name='last_invoice_sync_date',
            field=models.DateField(blank=True, help_text='Az utolsó szinkronizált számla módosítási dátuma (Billingo API last_modified_date filter)', null=True, verbose_name='Utolsó számla szinkronizálás dátuma'),
        ),
    ]
