# Generated by Django 4.2.7 on 2025-10-27 19:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bank_transfers', '0049_add_last_invoice_sync_date'),
    ]

    operations = [
        migrations.RenameField(
            model_name='companybillingosettings',
            old_name='last_invoice_sync_date',
            new_name='last_billingo_invoice_sync_date',
        ),
    ]
