# Generated by Django 4.2.7 on 2025-10-28 05:05

from django.db import migrations, models
import django.db.models.deletion


def add_base_tables_feature(apps, schema_editor):
    """Add BASE_TABLES feature template for ADMIN-only access"""
    FeatureTemplate = apps.get_model('bank_transfers', 'FeatureTemplate')

    feature_data = {
        'feature_code': 'BASE_TABLES',
        'display_name': 'Alaptáblák kezelése',
        'description': 'Beszállítók, Vevők és CONMED árak alaptáblák kezelése (ADMIN jogosultság szükséges)',
        'category': 'GENERAL',
        'default_enabled': False,
        'is_system_critical': False,
    }

    # Create feature template if it doesn't exist
    FeatureTemplate.objects.get_or_create(
        feature_code=feature_data['feature_code'],
        defaults=feature_data
    )


def remove_base_tables_feature(apps, schema_editor):
    """Remove BASE_TABLES feature template"""
    FeatureTemplate = apps.get_model('bank_transfers', 'FeatureTemplate')

    # Delete the feature template
    FeatureTemplate.objects.filter(feature_code='BASE_TABLES').delete()


class Migration(migrations.Migration):

    dependencies = [
        ('bank_transfers', '0050_rename_to_last_billingo_invoice_sync_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='companybillingosettings',
            name='last_billingo_invoice_sync_date',
            field=models.DateField(blank=True, help_text='Az utolsó szinkronizált Billingo számla módosítási dátuma (Billingo API last_modified_date filter)', null=True, verbose_name='Utolsó Billingo számla szinkronizálás dátuma'),
        ),
        migrations.CreateModel(
            name='Supplier',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Létrehozva')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Módosítva')),
                ('partner_name', models.CharField(max_length=255, verbose_name='Partner neve')),
                ('category', models.CharField(blank=True, help_text="Cost category (e.g., '1. TOTAL COST SALES:')", max_length=255, verbose_name='Kategória')),
                ('type', models.CharField(blank=True, help_text="Cost subcategory (e.g., 'Ortho', 'Rent, lease')", max_length=255, verbose_name='Típus')),
                ('valid_from', models.DateField(blank=True, help_text='Start date of validity period', null=True, verbose_name='Érvényesség kezdete')),
                ('valid_to', models.DateField(blank=True, help_text='End date of validity period (null = no expiry)', null=True, verbose_name='Érvényesség vége')),
                ('company', models.ForeignKey(help_text='A modell tulajdonosa', on_delete=django.db.models.deletion.CASCADE, to='bank_transfers.company', verbose_name='Cég')),
            ],
            options={
                'verbose_name': 'Beszállító',
                'verbose_name_plural': 'Beszállítók',
                'ordering': ['-id'],
                'indexes': [models.Index(fields=['company', 'valid_from', 'valid_to'], name='bank_transf_company_02910f_idx'), models.Index(fields=['partner_name'], name='bank_transf_partner_5eaa91_idx')],
            },
        ),
        migrations.CreateModel(
            name='ProductPrice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Létrehozva')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Módosítva')),
                ('product_value', models.CharField(help_text='Product code/identifier', max_length=50, verbose_name='Termék kód')),
                ('product_description', models.CharField(help_text='Product description', max_length=500, verbose_name='Termék leírás')),
                ('uom', models.CharField(blank=True, help_text="Unit of measure in English (e.g., 'EA')", max_length=50, verbose_name='UOM (EN)')),
                ('uom_hun', models.CharField(blank=True, help_text="Unit of measure in Hungarian (e.g., 'db')", max_length=50, verbose_name='UOM (HU)')),
                ('purchase_price_usd', models.DecimalField(blank=True, decimal_places=2, help_text='Purchase price in USD', max_digits=15, null=True, verbose_name='Beszerzési ár USD')),
                ('purchase_price_huf', models.DecimalField(blank=True, decimal_places=2, help_text='Purchase price in HUF', max_digits=15, null=True, verbose_name='Beszerzési ár HUF')),
                ('markup', models.DecimalField(blank=True, decimal_places=2, help_text='Markup percentage', max_digits=10, null=True, verbose_name='Markup (%)')),
                ('sales_price_huf', models.DecimalField(blank=True, decimal_places=2, help_text='Sales price in HUF', max_digits=15, null=True, verbose_name='Eladási ár HUF')),
                ('cap_disp', models.CharField(blank=True, help_text='Capital or Disposable classification', max_length=100, verbose_name='Cap/Disp')),
                ('is_inventory_managed', models.BooleanField(default=False, help_text="Whether this product is inventory-managed (Készletkezelt termék = 'y')", verbose_name='Készletkezelt termék')),
                ('valid_from', models.DateField(blank=True, help_text='Start date of validity period', null=True, verbose_name='Érvényesség kezdete')),
                ('valid_to', models.DateField(blank=True, help_text='End date of validity period (null = no expiry)', null=True, verbose_name='Érvényesség vége')),
                ('company', models.ForeignKey(help_text='A modell tulajdonosa', on_delete=django.db.models.deletion.CASCADE, to='bank_transfers.company', verbose_name='Cég')),
            ],
            options={
                'verbose_name': 'CONMED ár',
                'verbose_name_plural': 'CONMED árak',
                'ordering': ['-id'],
                'indexes': [models.Index(fields=['company', 'valid_from', 'valid_to'], name='bank_transf_company_a49297_idx'), models.Index(fields=['product_value'], name='bank_transf_product_433110_idx'), models.Index(fields=['company', 'product_value'], name='bank_transf_company_310803_idx')],
            },
        ),
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Létrehozva')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Módosítva')),
                ('customer_name', models.CharField(max_length=255, verbose_name='Vevő neve')),
                ('cashflow_adjustment', models.IntegerField(default=0, help_text='Number of days to adjust cashflow calculations (can be negative)', verbose_name='Cashflow kiigazítás (nap)')),
                ('valid_from', models.DateField(blank=True, help_text='Start date of validity period', null=True, verbose_name='Érvényesség kezdete')),
                ('valid_to', models.DateField(blank=True, help_text='End date of validity period (null = no expiry)', null=True, verbose_name='Érvényesség vége')),
                ('company', models.ForeignKey(help_text='A modell tulajdonosa', on_delete=django.db.models.deletion.CASCADE, to='bank_transfers.company', verbose_name='Cég')),
            ],
            options={
                'verbose_name': 'Vevő',
                'verbose_name_plural': 'Vevők',
                'ordering': ['-id'],
                'indexes': [models.Index(fields=['company', 'valid_from', 'valid_to'], name='bank_transf_company_2fe044_idx'), models.Index(fields=['customer_name'], name='bank_transf_custome_b40526_idx')],
            },
        ),
        migrations.RunPython(add_base_tables_feature, remove_base_tables_feature),
    ]
