# Generated by Django 4.2.7 on 2025-10-28 06:30

import csv
import os
from datetime import datetime
from decimal import Decimal, InvalidOperation
from django.db import migrations


def parse_date(date_str):
    """Parse date string in format YYYY/MM/DD or empty string"""
    if not date_str or not date_str.strip():
        return None
    try:
        # Handle YYYY/MM/DD format
        return datetime.strptime(date_str.strip(), '%Y/%m/%d').date()
    except ValueError:
        return None


def parse_decimal(value_str):
    """Parse decimal string, removing currency symbols and spaces"""
    if not value_str or not value_str.strip():
        return None
    try:
        # Remove currency symbols, spaces, and commas
        cleaned = value_str.strip().replace('$', '').replace('Ft', '').replace(' ', '').replace(',', '')
        return Decimal(cleaned)
    except (InvalidOperation, ValueError):
        return None


def import_suppliers(company, csv_file):
    """Import suppliers from CSV file"""
    Supplier = company.__class__.objects.model._meta.apps.get_model('bank_transfers', 'Supplier')
    count = 0

    with open(csv_file, 'r', encoding='utf-8') as f:
        reader = csv.DictReader(f)
        for row in reader:
            partner_name = row.get('Partner neve', '').strip()
            if not partner_name:
                continue

            # Check if already exists to make migration idempotent
            if Supplier.objects.filter(company=company, partner_name=partner_name).exists():
                continue

            Supplier.objects.create(
                company=company,
                partner_name=partner_name,
                category=row.get('Category', '').strip(),
                type=row.get('Type', '').strip(),
                valid_from=parse_date(row.get('Valid_from', '')),
                valid_to=parse_date(row.get('Valid_to', ''))
            )
            count += 1

    return count


def import_customers(company, csv_file):
    """Import customers from CSV file"""
    Customer = company.__class__.objects.model._meta.apps.get_model('bank_transfers', 'Customer')
    count = 0

    with open(csv_file, 'r', encoding='utf-8') as f:
        reader = csv.DictReader(f)
        for row in reader:
            customer_name = row.get('Customer name', '').strip()
            if not customer_name:
                continue

            # Check if already exists to make migration idempotent
            if Customer.objects.filter(company=company, customer_name=customer_name).exists():
                continue

            # Parse cashflow adjustment
            cashflow_str = row.get('Cashflow adjustment', '0').strip()
            try:
                cashflow_adjustment = int(cashflow_str) if cashflow_str else 0
            except ValueError:
                cashflow_adjustment = 0

            Customer.objects.create(
                company=company,
                customer_name=customer_name,
                cashflow_adjustment=cashflow_adjustment,
                valid_from=parse_date(row.get('Validf_from', '')),
                valid_to=parse_date(row.get('Valid_to', ''))
            )
            count += 1

    return count


def import_product_prices(company, csv_file):
    """Import product prices from CSV file - SKIPPING 'NEM KELL' column"""
    ProductPrice = company.__class__.objects.model._meta.apps.get_model('bank_transfers', 'ProductPrice')
    count = 0

    with open(csv_file, 'r', encoding='utf-8') as f:
        reader = csv.DictReader(f)
        for row in reader:
            product_value = row.get('Product Value', '').strip()
            product_description = row.get('Product Description', '').strip()

            if not product_value or not product_description:
                continue

            # Check if already exists to make migration idempotent
            if ProductPrice.objects.filter(company=company, product_value=product_value).exists():
                continue

            # Parse is_inventory_managed
            inventory_str = row.get('Készletkezelt termék', '').strip().lower()
            is_inventory_managed = inventory_str == 'y'

            ProductPrice.objects.create(
                company=company,
                product_value=product_value,
                product_description=product_description,
                # NOTE: Explicitly SKIPPING the "NEM KELL" column - it's not mapped to any field
                uom=row.get('UOM', '').strip(),
                uom_hun=row.get('UOM_HUN', '').strip(),
                purchase_price_usd=parse_decimal(row.get(' PURCHASE PRICE USD ', '')),
                purchase_price_huf=parse_decimal(row.get(' PURCHASE PRICE HUF ', '')),
                markup=parse_decimal(row.get(' MARKUP', '')),
                sales_price_huf=parse_decimal(row.get(' SALES PRICE HUF', '')),
                cap_disp=row.get('Cap/Disp', '').strip(),
                is_inventory_managed=is_inventory_managed,
                valid_from=parse_date(row.get('Valid from', '')),
                valid_to=parse_date(row.get('Valid to', ''))
            )
            count += 1

    return count


def import_base_tables_data(apps, schema_editor):
    """
    Import BASE_TABLES data from CSV files.

    Local: Uses 'IT Cardigan Kft.'
    Production: Uses 'MEDKA Kft.'
    """
    Company = apps.get_model('bank_transfers', 'Company')

    # Detect environment and select appropriate company
    # Try production company first
    try:
        company = Company.objects.get(name='MEDKA Kft.')
        print(f'📦 Importing BASE_TABLES data for PRODUCTION company: {company.name} (ID: {company.id})')
    except Company.DoesNotExist:
        # Fall back to local development company
        try:
            company = Company.objects.get(name='IT Cardigan Kft.')
            print(f'📦 Importing BASE_TABLES data for LOCAL company: {company.name} (ID: {company.id})')
        except Company.DoesNotExist:
            print('⚠️  Warning: Neither MEDKA Kft. nor IT Cardigan Kft. found. Skipping data import.')
            return

    # Get CSV file paths (relative to migrations directory)
    base_dir = os.path.dirname(os.path.dirname(os.path.dirname(__file__)))
    csv_dir = os.path.join(base_dir, 'bank_statement_example')

    suppliers_csv = os.path.join(csv_dir, 'BASE table - Beszallitok.csv')
    customers_csv = os.path.join(csv_dir, 'BASE table - Vevők.csv')
    prices_csv = os.path.join(csv_dir, 'BASE table - CONMED árak.csv')

    # Verify files exist
    for csv_file in [suppliers_csv, customers_csv, prices_csv]:
        if not os.path.exists(csv_file):
            print(f'❌ CSV file not found: {csv_file}')
            return

    # Import data with UTF-8 encoding
    print('📥 Importing suppliers...')
    suppliers_count = import_suppliers(company, suppliers_csv)
    print(f'   ✓ Imported {suppliers_count} suppliers')

    print('📥 Importing customers...')
    customers_count = import_customers(company, customers_csv)
    print(f'   ✓ Imported {customers_count} customers')

    print('📥 Importing product prices (skipping NEM KELL column)...')
    prices_count = import_product_prices(company, prices_csv)
    print(f'   ✓ Imported {prices_count} product prices')

    print(f'✅ Successfully imported all BASE_TABLES data for {company.name}')


def reverse_import_base_tables_data(apps, schema_editor):
    """
    Reverse migration - delete imported data.

    WARNING: This will delete all Suppliers, Customers, and ProductPrices
    for the target company!
    """
    Company = apps.get_model('bank_transfers', 'Company')
    Supplier = apps.get_model('bank_transfers', 'Supplier')
    Customer = apps.get_model('bank_transfers', 'Customer')
    ProductPrice = apps.get_model('bank_transfers', 'ProductPrice')

    # Detect environment and select appropriate company
    try:
        company = Company.objects.get(name='MEDKA Kft.')
    except Company.DoesNotExist:
        try:
            company = Company.objects.get(name='IT Cardigan Kft.')
        except Company.DoesNotExist:
            print('⚠️  Warning: Neither MEDKA Kft. nor IT Cardigan Kft. found. Skipping data deletion.')
            return

    print(f'🗑️  Deleting BASE_TABLES data for {company.name}...')

    suppliers_deleted = Supplier.objects.filter(company=company).delete()[0]
    customers_deleted = Customer.objects.filter(company=company).delete()[0]
    prices_deleted = ProductPrice.objects.filter(company=company).delete()[0]

    print(f'   ✓ Deleted {suppliers_deleted} suppliers')
    print(f'   ✓ Deleted {customers_deleted} customers')
    print(f'   ✓ Deleted {prices_deleted} product prices')


class Migration(migrations.Migration):

    dependencies = [
        ('bank_transfers', '0051_add_base_tables_feature'),
    ]

    operations = [
        migrations.RunPython(import_base_tables_data, reverse_import_base_tables_data),
    ]
