# Generated by Django 4.2.7 on 2025-10-28 08:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bank_transfers', '0052_import_base_tables_data'),
    ]

    operations = [
        migrations.AlterField(
            model_name='supplier',
            name='category',
            field=models.CharField(blank=True, choices=[('1. TOTAL COST SALES:', '1. TOTAL COST SALES:'), ('2. TOTAL PERSONNEL COSTS:', '2. TOTAL PERSONNEL COSTS:'), ('3. TOTAL OFFICE COSTS:', '3. TOTAL OFFICE COSTS:'), ('4. TOTAL COMPANY CARS COSTS:', '4. TOTAL COMPANY CARS COSTS:'), ('5. TOTAL MARKETING COSTS:', '5. TOTAL MARKETING COSTS:'), ('6. TOTAL CONSULTANTS COSTS:', '6. TOTAL CONSULTANTS COSTS:'), ('7. BANK & FINANCE:', '7. BANK & FINANCE:'), ('Disposable', 'Disposable'), ('Capital', 'Capital'), ('Unassigned', 'Unassigned')], help_text='Cost category', max_length=255, verbose_name='Kategória'),
        ),
        migrations.AlterField(
            model_name='supplier',
            name='type',
            field=models.CharField(blank=True, choices=[('Ortho', 'Ortho'), ('Rent, lease', 'Rent, lease'), ('Salaries & Wages', 'Salaries & Wages'), ('Salary related taxes', 'Salary related taxes'), ('Motor vehicle petrol', 'Motor vehicle petrol'), ('CONF/OPEN DAYS', 'CONF/OPEN DAYS'), ('OFFLINE ADS', 'OFFLINE ADS'), ('TRAVELLING COSTS', 'TRAVELLING COSTS'), ('IT & Communication', 'IT & Communication'), ('Accounting, tax, audit, transfer prices', 'Accounting, tax, audit, transfer prices'), ('Legal and tender consulation', 'Legal and tender consulation'), ('Banking costs', 'Banking costs'), ('Faktoring', 'Faktoring'), ('Repairs&Maintenance', 'Repairs&Maintenance'), ('Team building', 'Team building'), ('Trainings', 'Trainings'), ('Others', 'Others'), ('Disposable', 'Disposable'), ('Capital', 'Capital'), ('Unassigned', 'Unassigned')], help_text='Cost subcategory', max_length=255, verbose_name='Típus'),
        ),
    ]
