# Generated by Django 4.2.7 on 2025-10-28 08:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('bank_transfers', '0053_add_supplier_enum_choices'),
    ]

    operations = [
        migrations.CreateModel(
            name='SupplierType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Létrehozva')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Módosítva')),
                ('name', models.CharField(help_text='Cost subcategory name', max_length=255, verbose_name='Típus neve')),
                ('display_order', models.IntegerField(default=0, help_text='Display order (lower numbers appear first)', verbose_name='Megjelenítési sorrend')),
                ('company', models.ForeignKey(help_text='A modell tulajdonosa', on_delete=django.db.models.deletion.CASCADE, to='bank_transfers.company', verbose_name='Cég')),
            ],
            options={
                'verbose_name': 'Beszállító típus',
                'verbose_name_plural': 'Beszállító típusok',
                'ordering': ['display_order', 'name'],
            },
        ),
        migrations.CreateModel(
            name='SupplierCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Létrehozva')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Módosítva')),
                ('name', models.CharField(help_text='Cost category name', max_length=255, verbose_name='Kategória neve')),
                ('display_order', models.IntegerField(default=0, help_text='Display order (lower numbers appear first)', verbose_name='Megjelenítési sorrend')),
                ('company', models.ForeignKey(help_text='A modell tulajdonosa', on_delete=django.db.models.deletion.CASCADE, to='bank_transfers.company', verbose_name='Cég')),
            ],
            options={
                'verbose_name': 'Beszállító kategória',
                'verbose_name_plural': 'Beszállító kategóriák',
                'ordering': ['display_order', 'name'],
            },
        ),
        migrations.AlterField(
            model_name='supplier',
            name='category',
            field=models.ForeignKey(blank=True, help_text='Cost category', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='suppliers', to='bank_transfers.suppliercategory', verbose_name='Kategória'),
        ),
        migrations.AlterField(
            model_name='supplier',
            name='type',
            field=models.ForeignKey(blank=True, help_text='Cost subcategory', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='suppliers', to='bank_transfers.suppliertype', verbose_name='Típus'),
        ),
        migrations.AddIndex(
            model_name='suppliertype',
            index=models.Index(fields=['company', 'display_order'], name='bank_transf_company_e92ef4_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='suppliertype',
            unique_together={('company', 'name')},
        ),
        migrations.AddIndex(
            model_name='suppliercategory',
            index=models.Index(fields=['company', 'display_order'], name='bank_transf_company_c797b9_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='suppliercategory',
            unique_together={('company', 'name')},
        ),
    ]
