# Generated by Django 4.2.7 on 2025-10-28 08:45

from django.db import migrations


def populate_defaults(apps, schema_editor):
    """Populate default categories and types for all companies"""
    Company = apps.get_model('bank_transfers', 'Company')
    SupplierCategory = apps.get_model('bank_transfers', 'SupplierCategory')
    SupplierType = apps.get_model('bank_transfers', 'SupplierType')

    categories = [
        (1, '1. TOTAL COST SALES:'),
        (2, '2. TOTAL PERSONNEL COSTS:'),
        (3, '3. TOTAL OFFICE COSTS:'),
        (4, '4. TOTAL COMPANY CARS COSTS:'),
        (5, '5. TOTAL MARKETING COSTS:'),
        (6, '6. TOTAL CONSULTANTS COSTS:'),
        (7, '7. BANK & FINANCE:'),
    ]

    types = [
        (1, 'Ortho'),
        (2, 'Rent, lease'),
        (3, 'Salaries & Wages'),
        (4, 'Salary related taxes'),
        (5, 'Motor vehicle petrol'),
        (6, 'CONF/OPEN DAYS'),
        (7, 'OFFLINE ADS'),
        (8, 'TRAVELLING COSTS'),
        (9, 'IT & Communication'),
        (10, 'Accounting, tax, audit, transfer prices'),
        (11, 'Legal and tender consulation'),
        (12, 'Banking costs'),
        (13, 'Faktoring'),
        (14, 'Repairs&Maintenance'),
        (15, 'Team building'),
        (16, 'Trainings'),
        (17, 'Others'),
    ]

    for company in Company.objects.all():
        for display_order, name in categories:
            SupplierCategory.objects.get_or_create(
                company=company,
                name=name,
                defaults={'display_order': display_order}
            )

        for display_order, name in types:
            SupplierType.objects.get_or_create(
                company=company,
                name=name,
                defaults={'display_order': display_order}
            )


def reverse_populate(apps, schema_editor):
    """Remove all categories and types"""
    SupplierCategory = apps.get_model('bank_transfers', 'SupplierCategory')
    SupplierType = apps.get_model('bank_transfers', 'SupplierType')
    SupplierCategory.objects.all().delete()
    SupplierType.objects.all().delete()


class Migration(migrations.Migration):

    dependencies = [
        ('bank_transfers', '0054_create_supplier_category_type_tables'),
    ]

    operations = [
        migrations.RunPython(populate_defaults, reverse_populate),
    ]
