# Generated by Django 4.2.7 on 2025-10-28 10:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('bank_transfers', '0055_populate_default_categories_types'),
    ]

    operations = [
        migrations.AddField(
            model_name='companybillingosettings',
            name='last_billingo_spending_sync_date',
            field=models.DateField(blank=True, help_text='Az utolsó szinkronizált Billingo költség módosítási dátuma', null=True, verbose_name='Utolsó Billingo költség szinkronizálás dátuma'),
        ),
        migrations.CreateModel(
            name='BillingoSpending',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Létrehozva')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Módosítva')),
                ('id', models.BigIntegerField(primary_key=True, serialize=False)),
                ('organization_id', models.IntegerField(verbose_name='Billingo szervezet ID')),
                ('category', models.CharField(choices=[('advertisement', 'Hirdetés'), ('development', 'Fejlesztés'), ('other', 'Egyéb'), ('overheads', 'Rezsiköltség'), ('service', 'Szolgáltatás'), ('stock', 'Készlet'), ('tangible_assets', 'Tárgyi eszköz')], max_length=20, verbose_name='Kategória')),
                ('paid_at', models.DateField(blank=True, null=True, verbose_name='Kiegyenlítés dátuma')),
                ('fulfillment_date', models.DateField(verbose_name='Teljesítés dátuma')),
                ('invoice_number', models.CharField(max_length=100, verbose_name='Számla/Bizonylat száma')),
                ('currency', models.CharField(default='HUF', max_length=3, verbose_name='Deviza')),
                ('conversion_rate', models.DecimalField(decimal_places=6, default=1, max_digits=10, verbose_name='Átváltási árfolyam')),
                ('total_gross', models.DecimalField(decimal_places=2, max_digits=15, verbose_name='Bruttó összeg')),
                ('total_gross_local', models.DecimalField(decimal_places=2, max_digits=15, verbose_name='Bruttó összeg (HUF)')),
                ('total_vat_amount', models.DecimalField(decimal_places=2, max_digits=15, verbose_name='ÁFA összeg')),
                ('total_vat_amount_local', models.DecimalField(decimal_places=2, max_digits=15, verbose_name='ÁFA összeg (HUF)')),
                ('invoice_date', models.DateField(verbose_name='Számla kelte')),
                ('due_date', models.DateField(verbose_name='Fizetési határidő')),
                ('payment_method', models.CharField(help_text='wire_transfer, cash, card, stb.', max_length=30, verbose_name='Fizetési mód')),
                ('partner_id', models.IntegerField(blank=True, null=True, verbose_name='Partner ID')),
                ('partner_name', models.CharField(max_length=255, verbose_name='Partner neve')),
                ('partner_tax_code', models.CharField(blank=True, max_length=50, verbose_name='Partner adószáma')),
                ('partner_address', models.JSONField(blank=True, help_text='Full address object from API', null=True, verbose_name='Partner címe')),
                ('partner_iban', models.CharField(blank=True, max_length=100, verbose_name='Partner IBAN')),
                ('partner_account_number', models.CharField(blank=True, max_length=100, verbose_name='Partner bankszámla')),
                ('comment', models.TextField(blank=True, verbose_name='Megjegyzés')),
                ('is_created_by_nav', models.BooleanField(default=False, help_text='True if spending was created from NAV import', verbose_name='NAV által létrehozva')),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='billingo_spendings', to='bank_transfers.company', verbose_name='Cég')),
            ],
            options={
                'verbose_name': 'Billingo költség',
                'verbose_name_plural': 'Billingo költségek',
                'ordering': ['-invoice_date'],
                'indexes': [models.Index(fields=['company', 'invoice_date'], name='bank_transf_company_d8f548_idx'), models.Index(fields=['company', 'category'], name='bank_transf_company_f7e559_idx'), models.Index(fields=['company', 'paid_at'], name='bank_transf_company_49d2b1_idx'), models.Index(fields=['partner_tax_code'], name='bank_transf_partner_b625c2_idx'), models.Index(fields=['invoice_number'], name='bank_transf_invoice_f8a703_idx')],
            },
        ),
    ]
