# Generated by Django 4.2.7 on 2025-10-28 12:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bank_transfers', '0056_add_billingo_spending'),
    ]

    operations = [
        migrations.AlterField(
            model_name='billingospending',
            name='category',
            field=models.CharField(choices=[('advertisement', 'Hirdetés'), ('development', 'Fejlesztés'), ('education_and_training', 'Oktatás és képzés'), ('other', 'Egyéb'), ('overheads', 'Rezsiköltség'), ('service', 'Szolgáltatás'), ('stock', 'Készlet'), ('tangible_assets', 'Tárgyi eszköz')], max_length=30, verbose_name='Kategória'),
        ),
        migrations.AlterField(
            model_name='billingospending',
            name='partner_account_number',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Partner bankszámla'),
        ),
        migrations.AlterField(
            model_name='billingospending',
            name='partner_iban',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Partner IBAN'),
        ),
    ]
