# Generated by Django 4.2.7 on 2025-10-31 05:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bank_transfers', '0057_fix_billingo_spending_schema'),
    ]

    operations = [
        migrations.AlterField(
            model_name='banktransaction',
            name='payer_name',
            field=models.CharField(blank=True, db_index=True, max_length=300, verbose_name='Fizető fél neve'),
        ),
    ]
