# Generated by Django 4.2.7 on 2025-11-01 07:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bank_transfers', '0058_increase_payer_name_length'),
    ]

    operations = [
        migrations.AddField(
            model_name='billingoinvoice',
            name='net_total',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True, verbose_name='Nettó összeg'),
        ),
    ]
