# Generated by Django 4.2.7 on 2025-11-03 13:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('bank_transfers', '0059_add_net_total_to_billingo_invoice'),
    ]

    operations = [
        migrations.CreateModel(
            name='BillingoRelatedDocument',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Létrehozva')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Módosítva')),
                ('related_invoice_id', models.BigIntegerField(help_text='Billingo invoice ID of the related document', verbose_name='Kapcsolódó számla ID')),
                ('related_invoice_number', models.CharField(help_text='Invoice number of the related document', max_length=100, verbose_name='Kapcsolódó számlaszám')),
                ('invoice', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='related_documents', to='bank_transfers.billingoinvoice', verbose_name='Számla')),
            ],
            options={
                'verbose_name': 'Kapcsolódó Billingo dokumentum',
                'verbose_name_plural': 'Kapcsolódó Billingo dokumentumok',
                'ordering': ['related_invoice_number'],
                'indexes': [models.Index(fields=['invoice', 'related_invoice_id'], name='bank_transf_invoice_ecbbe7_idx'), models.Index(fields=['related_invoice_id'], name='bank_transf_related_bd6c5c_idx')],
            },
        ),
    ]
