# Generated by Django 4.2.7 on 2025-11-08 08:21

from decimal import Decimal
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('bank_transfers', '0060_add_billingo_related_documents'),
    ]

    operations = [
        migrations.AlterField(
            model_name='banktransaction',
            name='matched_invoice',
            field=models.ForeignKey(blank=True, help_text='(DEPRECATED) Use matched_invoices instead - single invoice match', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='bank_transactions', to='bank_transfers.invoice', verbose_name='Párosított számla'),
        ),
        migrations.CreateModel(
            name='BankTransactionInvoiceMatch',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('match_confidence', models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Match confidence score (0.00-1.00)', max_digits=4, verbose_name='Párosítás megbízhatósága')),
                ('match_method', models.CharField(blank=True, choices=[('REFERENCE_EXACT', 'Reference Exact Match'), ('AMOUNT_IBAN', 'Amount + IBAN Match'), ('BATCH_INVOICES', 'Batch Invoice Match'), ('FUZZY_NAME', 'Fuzzy Name Match'), ('AMOUNT_DATE_ONLY', 'Amount + Date Only'), ('MANUAL', 'Manual Single Match'), ('MANUAL_BATCH', 'Manual Batch Match')], help_text='Matching method used (BATCH_INVOICES, MANUAL_BATCH, etc.)', max_length=50, verbose_name='Párosítási módszer')),
                ('matched_at', models.DateTimeField(auto_now_add=True, help_text='When the match was created', verbose_name='Párosítás időpontja')),
                ('match_notes', models.TextField(blank=True, help_text='Detailed match information for audit trail', verbose_name='Párosítási megjegyzések')),
                ('invoice', models.ForeignKey(help_text='The NAV invoice that was matched', on_delete=django.db.models.deletion.CASCADE, related_name='transaction_matches', to='bank_transfers.invoice', verbose_name='NAV számla')),
                ('matched_by', models.ForeignKey(blank=True, help_text='User who created manual match (NULL for automatic)', null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Párosította')),
                ('transaction', models.ForeignKey(help_text='The bank transaction that was matched', on_delete=django.db.models.deletion.CASCADE, related_name='invoice_matches', to='bank_transfers.banktransaction', verbose_name='Bank tranzakció')),
            ],
            options={
                'verbose_name': 'Tranzakció-számla párosítás',
                'verbose_name_plural': 'Tranzakció-számla párosítások',
                'db_table': 'bank_transfers_banktransactioninvoicematch',
                'ordering': ['transaction', 'invoice'],
            },
        ),
        migrations.AddField(
            model_name='banktransaction',
            name='matched_invoices',
            field=models.ManyToManyField(blank=True, help_text='Multiple matched invoices (for batch payments)', related_name='bank_transactions_many', through='bank_transfers.BankTransactionInvoiceMatch', to='bank_transfers.invoice', verbose_name='Párosított számlák'),
        ),
        migrations.AddIndex(
            model_name='banktransactioninvoicematch',
            index=models.Index(fields=['transaction', 'invoice'], name='idx_tx_invoice_match'),
        ),
        migrations.AddIndex(
            model_name='banktransactioninvoicematch',
            index=models.Index(fields=['invoice'], name='idx_invoice_matches'),
        ),
        migrations.AlterUniqueTogether(
            name='banktransactioninvoicematch',
            unique_together={('transaction', 'invoice')},
        ),
    ]
