# Generated by Django 4.2.7 on 2025-11-08 08:23

from decimal import Decimal
from django.db import migrations


def migrate_existing_matches_forward(apps, schema_editor):
    """
    Migrate existing matched_invoice (ForeignKey) data to matched_invoices (ManyToMany).

    For each BankTransaction with matched_invoice set:
    1. Create BankTransactionInvoiceMatch record
    2. Link transaction to invoice via the through table
    3. Set confidence=0.95 (legacy match, assumed valid)
    4. Set method='MANUAL' (unknown original method)
    """
    BankTransaction = apps.get_model('bank_transfers', 'BankTransaction')
    BankTransactionInvoiceMatch = apps.get_model('bank_transfers', 'BankTransactionInvoiceMatch')

    migrated_count = 0
    transactions_with_matches = BankTransaction.objects.filter(matched_invoice__isnull=False)

    for transaction in transactions_with_matches:
        # Create the match record in the through table
        BankTransactionInvoiceMatch.objects.create(
            transaction=transaction,
            invoice=transaction.matched_invoice,
            match_confidence=Decimal('0.95'),  # Legacy match - assumed valid
            match_method='MANUAL',  # Unknown original method
            match_notes='Migrated from legacy matched_invoice field'
        )
        migrated_count += 1

    print(f"✅ Migrated {migrated_count} existing invoice matches to ManyToMany relationship")


def migrate_existing_matches_reverse(apps, schema_editor):
    """
    Reverse migration: Remove all BankTransactionInvoiceMatch records.

    This allows rolling back to the old ForeignKey-only system.
    Note: matched_invoice field is preserved, so data is not lost.
    """
    BankTransactionInvoiceMatch = apps.get_model('bank_transfers', 'BankTransactionInvoiceMatch')

    deleted_count = BankTransactionInvoiceMatch.objects.count()
    BankTransactionInvoiceMatch.objects.all().delete()

    print(f"✅ Rolled back {deleted_count} invoice matches from ManyToMany relationship")


class Migration(migrations.Migration):

    dependencies = [
        ('bank_transfers', '0061_add_batch_invoice_matching'),
    ]

    operations = [
        migrations.RunPython(
            migrate_existing_matches_forward,
            reverse_code=migrate_existing_matches_reverse
        ),
    ]
